.github/PULL_REQUEST_TEMPLATE.md
The template itself won't be used to make a PR until the template is on the default branch of the repo.
There is currently a Trello ticket for this https://trello.com/c/0dcsuovn but I decided to push it forward and submit it. Thanks for the help Jason
This is a starting point and we can see how it works and make changes as we go on with the project. If the template were available it would look like the following
---
None.
We currently don’t have a standard template for creating PR descriptions. This makes it difficult to review PRs. It also allows for novice programmers to create bad PRs forcing other programmers to spend more time than necessary on a PR. Finally, without proper PR …
=> Added initial pull request template

main.js
[Github 38](https://github.com/CityOfZion/neon-wallet/issues/38)
Quit the app once all the windows are closed.
Added a listener which will close the app on window-all-closed.
Manual testing on Sierra 10.12.4, I don't have a windows/linux machine to test on right now.
Nope
Nope
=> #38 avoiding the app to 'freeze' in dock after being closed

app/components/CreateWallet.js, app/components/WalletInfo.js
https://github.com/CityOfZion/neon-wallet/issues/46
It enables the user to use the copy-to-clipboard button again. Tested on Arch Linux
the `clipboard.writeText()` function has a next to the actual text a second type parameter. This type parameter seems to make problems. Without this optional parameter, the text is copied to the clipboard properly. 
See here: https://github.com/electron/electron/blob/master/docs/api/clipboard.md
I tested in on my local PC (Arch Linux with Gnome 3.24)
I don't think so
**Is there anything else we should …
=> fixes issue with not working copy-to-clipboard button

app/components/TransactionHistory.js
None.
React warning message appeared in the console because sibling elements need some sort of unique identifier when they're created with functions such as `map`
Added key property to `li` element that is the transaction id `t.txid`
No console warning
None
No
https://fb.me/react-warning-keys
=> Added key property to transaction array li element

README.md
I admit this is a very trivial change, very low priority. This PR fixes the link to the Reddits sub-channel that was improperly linking to the Slack account.
=> Fix link to NEO sub-Reddit

__tests__/components/TransactionHistory.test.js, __tests__/components/WalletInfo.test.js, __tests__/components/__snapshots__/WalletInfo.test.js.snap, app/components/WalletInfo.js, app/modules/account.js, app/modules/claim.js, app/modules/dashboard.js, app/modules/generateWallet.js, app/modules/metadata.js, app/modules/transactions.js, app/modules/wallet.js, package.json
…to separate file
testing the neon wallet WalletInfo component - I also exported the action type constants so they are easier to access for testing
testing the WalletInfo component
writing functionality and snapshot tests
running npm test
there is a need for a try/ catch in some of the async tests to solve a problem I was having with this error message:
"Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."
Even though no errors were getting caught, the try/ catch blocks are needed and …
=> add tests for WalletInfo component

README.md, package.json
N/A
You shouldn't have to install global versions of Webpack and Jest since they already get installed via `npm install`. 
Move calls to webpack into `npm scripts` so that the dependency bundle can be accessed directly. 
I called the scripts `assets` and `assets-watch` to keep them resilient to a future in which another asset bundler is used instead of `webpack`. 
I also got rid of a console warning being sent from the `postinstall` script by changing `install-app-deps` to `electron-builder install-app-deps`
Updates README to reflect these changes. 
Manually ran `npm run assets` `npm run assets-watch`
**Are …
=> Remove requirement to globally install Webpack and Jest

__tests__/components/WalletInfo.test.js
testing Neon Wallet
There is a setTimeout of 1 second for clearTransaction() that needed to execute at the end of refreshBalance, so the setTimeout in the test needed some extra time to run.
increasing the setTimeout length. also, the store.getActions() length increased to 11
I ran 'npm test' several times. I wanted to test different timeout lengths and make sure the number of returned actions was always 11.
no
=> fix async issue with test

package.json, yarn.lock
This is part of a general refactor to enhance the developer experience with Neon Wallet.
Adds a `prepush` command to the scripts using husky (https://github.com/typicode/husky).
It will run the lint & tests on each push.
Its possible to override this behaviour for a quick push using:
`git push ... --no-verify`
I think its great because it allows the developer to know that the commits were adhering to the tests/lint rules.
Added husky and the prepush command.
I tested it.
=> Adds husky & prepush hook

__mocks__/neon-js.js, __tests__/components/Send.test.js
testing neon wallet
Fixes an issue I was having with one of the tests in Send.test.js. Also, I handled some of the neon-js mock promise rejections differently after seeing some comments in my eslint recommendations not to have unhandled promises.
add a promise that resolves to give the event loop an extra cycle. nothing else like a standard setTimeout(() => {}, 0) or process.nextTick would work here
running npm test
no
=> fix timing related issue with one of the tests in Send

app/components/EncryptKey.js, app/components/LoginLocalStorage.js, app/components/LoginTokenSale.js
The wallet doesn't check for empty input fields and gives the user no notification message if a field is required or empty. This PR addresses several of those cases, but not necessarily all of them.
=> Empty Field Checking and User Notification Messages

app/store/configureStore.dev.js, package.json, yarn.lock
Developer experience improvement.
The end of console logging your actions/state.
Added the redux-logger package to the configureStore.dev file.
Tested it, currently there are some unrelated lint/flow errors. (Will be fixed soon)
=> Adds redux-logger (dev only)

main.js
I don't think this has been reported previously.
Fixes the spelling of the "GitHub" menu item.
Changed the hardcoded text in `main.js`.
Built and verified the app on my local.
No
No
=> Fixing spelling of GitHub menu item

__mocks__/electron.js, __tests__/core/explorer.test.js, app/components/Settings.js, app/core/constants.js, app/core/explorer.js
This PR supports the effort to add unit tests (#34).
This adds support for the NeoScan explorer (alongside NeoTracker and AntChain). Since NeoScan is CoZ's tracker, it seems like it should be supported. Also, NeoTracker's testnet site has an HSTS error, so adding a third explorer option adds some redundancy.
Additionally, it adds full test coverage for the `app/core/explorer.js` file.
This PR adds an option for the NeoScan explorer following the model of the NeoTracker and AntChain explorers.
This PR also adds unit tests for explorer functionality in `__tests__/core/explorer.test.js`.
I manually tested …
=> Adding support for Neoscan explorer

.circleci/config.yml
I mentioned this idea in #251.
Currently the flow checks are not performed as part of the CircleCI tasks, so a flow error does not trigger CI error reporting to GitHub.
Added the `yarn flow` command to the build job. I added it there because I thought it made sense to couple with `yarn lint`.
The CircleCI report for this PR will demonstrate it.
no
no
- [n/a] Unit tests written?
=> Adding flow check to CircleCI configuration

app/components/Home/Home.jsx
Token sale is currently broken
Hides the button (does not remove the actual code)
=> Hides the token sale page for 0.0.7 release

package.json, yarn.lock
Fixed style.css loading when building electron app
also updated node-sass so it would work with nodejs 8.9
#295
#296 
added a file to the build settings in package.json
it was completely broken, now it works.
=> Fixed style.css loading when building electron app

__tests__/components/Modals/ConfirmModal.test.js, __tests__/components/Modals/__snapshots__/ConfirmModal.test.js.snap, __tests__/store/reducers.test.js, app/components/Modals/BaseModal/BaseModal.jsx, app/components/Modals/BaseModal/BaseModal.scss, app/components/Modals/BaseModal/index.js, app/components/Modals/ConfirmModal/ConfirmModal.jsx, app/components/Modals/ConfirmModal/ConfirmModal.scss, app/components/Modals/ConfirmModal/index.js, app/containers/App/App.jsx, app/containers/ModalRenderer/ModalRenderer.jsx, app/containers/ModalRenderer/index.js, app/containers/Settings/Settings.jsx, app/containers/Settings/index.js, app/core/constants.js, app/core/time.js, app/flow-typed/declarations.js, app/modules/modal.js, app/store/reducers.js, app/styles/main.global.scss, package.json, yarn.lock
Modals will be used for both NEP5 and Address Book.
Adds a modal infrastructure with two generic modals.
BaseModal which should be the base modal for all modals, and a ConfirmModal (which uses BaseModal).
I used ReactModal + Tiny reducer for managing the state of modals.
Ensured all tests work + manual QA.
I replaced the `window.confirm...` we had in Settings for saved wallet deletion in favour of the ConfirmModal.
Maybe we will need to redesign it.
Yep.
=> Add modal infrastructure + confirm modal for deleting a wallet

.babelrc, package.json, yarn.lock
Tech debt
Babel-preset-2015 has been replaced by babel-preset-env, this is a recommended upgrade.
QA'ed everything
=> [Tech Debt] Replace babel-preset-2015 with babel-preset-env

__tests__/components/NetworkSwitch.test.js, __tests__/components/TransactionHistory.test.js, __tests__/components/WalletInfo.test.js, __tests__/components/__snapshots__/TransactionHistory.test.js.snap, __tests__/modules/transactions.test.js, app/components/Loader/Loader.jsx, app/components/Loader/Loader.scss, app/components/Loader/index.js, app/containers/NetworkSwitch/NetworkSwitch.scss, app/containers/TransactionHistory/TransactionHistory.jsx, app/containers/TransactionHistory/TransactionHistory.scss, app/containers/TransactionHistory/Transactions.jsx, app/containers/TransactionHistory/Transactions.scss, app/containers/TransactionHistory/index.js, app/modules/transactions.js, app/styles/main.global.scss, app/styles/variables.scss
None
Add a loading indicator + an empty state message when there are no transactions.
I added a Loader component, isLoading state to the transactions reducer, and split the transactions into their own component.
Currently, some tests fail. This is a WIP.
=> Add loader to transaction history (WIP)

app/modules/claim.js, app/modules/dashboard.js, app/modules/rpx.js, app/modules/transactions.js, app/modules/wallet.js
General wallet improvements
When a user logged out and then logged in again (maybe with a different wallet), there would be a flash of "old" values. This is because it was not cleared when the user logged out.
Cleared (back to initialState) the states of: wallet/claim/dashboard/rpx/transactions
I tried logging in using various wallets, and now the state is clean and there is no flash of old values.
=> Clear state after logout

__tests__/components/Login.test.js, __tests__/components/LoginNep2.test.js, __tests__/components/__snapshots__/Login.test.js.snap, app/components/PasswordField/PasswordField.jsx, app/components/PasswordField/PasswordField.scss, app/components/PasswordField/index.js, app/containers/CreateWallet/CreateWallet.jsx, app/containers/EncryptKey/EncryptKey.jsx, app/containers/LoginLocalStorage/LoginLocalStorage.jsx, app/containers/LoginNep2/LoginNep2.jsx, app/containers/LoginPrivateKey/LoginPrivateKey.jsx, app/styles/login.scss
Github #342
Some fields that should default to type "password" don't and they also need the password/text (eye logo) toggle
Made a new reusable component
Try out all the wallet login screens
No
No
=> Fix for: Password is displayed as visible text when creating wallet #342

__tests__/components/WalletInfo.test.js, app/containers/WalletInfo/WalletInfo.jsx
Github #265
Shows an error if the app can't get wallet balance
On init, it's using the standard refresh method which already has the correct error checking
Disconnect internet.
No
No
Yes!
=> Fix for: Give warning when API is down or wallet lacks connectivity #265

app/containers/LoginTokenSale/LoginTokenSale.jsx
This screen isn't available yet but I saw it wasn't using the new password field so I did a quick update.
=> Use PasswordField for WIF key in secret token sale screen

main.js
#336
Right Click on input doesn't do anything. You should see a menu with cut / copy / past / select all options
Add Electron menu input config
Tests
=> Add Cut/Copy/Paste context menus on input fields (#336)

app/components/Modals/SendModal/ConfirmDisplay.jsx, app/components/Modals/SendModal/SendDisplay.jsx, app/components/Modals/SendModal/SendModal.scss
UI Touch ups
Send modal touch ups:
1. Add an info message when selecting a NEP5 token, indicating that there is a need for at least 1 drop of gas when sending a token.
2. Remove the margin from the last percent button.
3. Remember selected value of assets (when returning from confirm display)
3. Remove extra div in confirm display.
Tested
No
=> Send modal ui fixes

app/containers/WalletInfo/TokensBalance.jsx, app/containers/WalletInfo/TokensBalance.scss
UI Touch ups
Token balance touch ups:
1. Add a tooltip displaying the full balance of the token balance.
2. Correct the height issue with the table cell. (one was 28px, the other 29px)
3. Center the token symbol.
Tested
No
=> Token balance ui fixes

app/containers/DisplayWalletKeys/DisplayWalletKeys.jsx, app/containers/DisplayWalletKeys/index.js
https://github.com/CityOfZion/neon-wallet/issues/396
Currently you can accidentally save over preexisting keys by using a key name you've used before.
Warn the user in a confirmation overlay. They can confirm overwriting the key or cancel and choose a different name.
Save a new key "test". Create another key and try to name it "test"
no
no
Overlay looks like this in case language/design changes are needed:
=> Show a warning when trying to save a key with the same name

app/components/Modals/SendModal/ConfirmDisplay.jsx, app/components/Modals/SendModal/SendModal.scss
https://github.com/CityOfZion/neon-wallet/issues/271
Check NeonDB tx history for recipient address transactions. If there are none, show warning
Check the UI sending to fresh throwaway address.
=> Warn user when address being sent to has no transaction history

app/components/Modals/ReceiveModal/ReceiveModal.jsx, app/components/Modals/ReceiveModal/ReceiveModal.scss, app/components/Modals/SendModal/ConfirmDisplay.jsx, app/components/Modals/SendModal/SendModal.jsx, app/containers/Dashboard/Dashboard.jsx
=> add and format from address with link

app/components/Modals/ReceiveModal/ReceiveModal.jsx
None
Increase height to remove the scroll (See screenshot)
=> Bugfix: [Receive Modal] - Increase the height to hide the scroll

app/containers/Settings/Settings.jsx
None
`getCurrencyOptions` function was using ES5.
I used ES6 + `map` instead of `forEach`
=> Small refactor to a function

app/modules/account.js, app/modules/claim.js, app/modules/transactions.js
=> refactor send asset function code

README.md
N/A
The README still linked to Slack instead of Discord.
I replaced the Slack link and text with Discord link and text.
I clicked the link.
No.
No.
N/A
=> Replaced readme slack link with discord link

__tests__/components/Inputs/AddressInput/AddressInput.test.js, __tests__/components/Inputs/AddressInput/__snapshots__/AddressInput.test.js.snap, __tests__/components/Inputs/SelectInput/SelectInput.test.js, __tests__/components/Inputs/SelectInput/__snapshots__/SelectInput.test.js.snap, __tests__/store/reducers.test.js, app/components/Inputs/AddressInput/AddressInput.jsx, app/components/Inputs/AddressInput/AddressInput.scss, app/components/Inputs/AddressInput/SaveIcon.jsx, app/components/Inputs/AddressInput/SaveIcon.scss, app/components/Inputs/AddressInput/index.js, app/components/Inputs/SelectInput/Dropdown.jsx, app/components/Inputs/SelectInput/Dropdown.scss, app/components/Inputs/SelectInput/SelectInput.jsx, app/components/Inputs/SelectInput/SelectInput.scss, app/components/Inputs/SelectInput/index.js, app/components/Modals/SendModal/SendDisplay.jsx, app/components/Modals/SendModal/SendModal.jsx, app/modules/addressBook.js, app/modules/index.js, package.json, yarn.lock
Finishes #9.
It allows users to save & name addresses that they commonly send assets to.  There are simple mechanisms for saving (only valid addresses) with custom unique names, as well as deleting addresses that are no longer needed.
I modified the existing "Send" modal to extend the behavior of the recipient address text input.  It is now composed of a more complex set of react components that represent a select input w/ drop-down of existing values (if any values have been added yet).
When the user focuses on the input, it expands the drop-down to show existing values.  As the user starts typing, the values are filtered (by both address & name) to …
=> Added address book management for sending assets

__tests__/components/__snapshots__/Claim.test.js.snap, app/containers/Claim/Claim.jsx
N/A
The "Claim GAS" button was showing exponential values.
Before:
After:
Used the existing `formatGAS` helper function.
Smoke tested it, compared output to snapshot in tests.
N/A
N/A
=> Fixed claim button formatting

__tests__/modules/wallet.test.js, app/core/constants.js
N/A
It supports sending & showing balance for DBC (DeepBrain Coin), similar to RPX.
I added the MainNet & TestNet constants for the DBC hash.
I loaded the wallet and confirmed that I can view the 0 DBC balance & view DBC token information by clicking on the balance.  **NOTE:** I was unable to test transferring DBC due to having a 0 balance.
N/A
See **NOTE** above.
=> Added DeepBrain Coin

__tests__/components/Blockchain/Address/Address.test.js, __tests__/components/Blockchain/Address/__snapshots__/Address.test.js.snap, app/components/Blockchain/Address/Address.jsx, app/components/Blockchain/Address/Address.scss, app/components/Blockchain/Address/index.js, app/components/Modals/ReceiveModal/ReceiveModal.jsx, app/components/Modals/SendModal/ConfirmDisplay.jsx, app/components/Modals/SendModal/SendModal.jsx, app/containers/Dashboard/Dashboard.jsx, app/containers/Dashboard/index.js
N/A
It cleans up `net` and `explorer` props being passed down a chain of react components just to feed them into the `Address` component.  Instead, we can fetch these from the redux store when rendering this component.
I also added a simple test for the `Address` component itself.
I removed the excess props being passed to individual components, and I added a store lookup for the `Address` component itself.
I smoke tested the app and clicked the address link anywhere it's used.  It took me to the correct explorer running on the correct network.
**Are there any special changes in the code that we should be …
=> Address redux state

app/core/explorer.js
N/A
The function for opening asset links in a block explorer was using the wrong method internally, which would cause a transaction page to be loaded with an invalid txid.
I swapped out the wrong internal function call with the correct one.
N/A because it's not being used anywhere yet.
N/A
N/A
=> Fixed assets linking to wrong URL

__tests__/components/__snapshots__/TransactionHistory.test.js.snap, app/containers/TransactionHistory/index.js
N/A
Fetching the transaction sometimes fails, hitting localhost instead of the intended API endpoint based upon the current network.
I added the `net` prop to the `TransactionHistory` component since it was missing.
I'm not confident because I could not reproduce.  My change is based upon some insight from @dvdschwrtz where he stated that a call to `syncTransactionHistory` is receiving `undefined` for the network argument.  The `TransactionHistory` component is the only place that function is called, and we are incorrectly not passing the `net` prop to that component.
**Are there any special changes in the …
=> Fixed net being undefined sometimes when fetching transaction history

app/components/Modals/SendModal/AddRecipientDisplay.jsx, app/core/math.js
Fixes max button, a formatted string was passed instead of the actual balance.
This is a quick fix for now, but will add more defensive coding and tests for this.
=> Fix MAX button

app/components/Modals/SendModal/ConfirmDisplay.jsx, app/components/Modals/SendModal/ConfirmDisplay.scss, app/components/Modals/SendModal/SendModal.jsx, app/components/Modals/SendModal/withAddressCheck.jsx
N/A
* Adds a delete icon for removing a recipient from the "Send" modal.
* Fixes the cursor for the "Add Recipient" link.
I added a trash can icon that, when clicked, removes the "send entry" from the array of entries tracked in the `SendModal` component state.  I also updated the balance that is tracked for the asset/token when an entry is deleted to ensure that the available amount accurately reflects what isn't accounted for by entries.
Smoke tested adding single/multiple entries, removing them, and validating that the available balance displayed in the modal (below the `NumberInput`) matches the expected …
=> Delete send recipients

app/containers/TransactionHistory/Transactions.jsx
N/A
The transaction history was unintentially very verbose for 0-asset transactions.  This was caused by a change to use BigNumber that wasn't accounted for in the transaction history component.
*Before:*
*After:*
I changed the equality check for numbers to use BigNumber's `equals` function instead of JS `===`.
Smoke tested (see attached before/after screenshots).
N/A
N/A
=> Fixed transaction history verbosity

__tests__/modules/wallet.test.js, app/core/constants.js
DISCLAIMER:
I am not affiliated with RHT. I just happen to [discover it recently](https://steemit.com/cryptocurrency/@weppos/rht-token-redeemable-hashpuppy-token) and being a NEO user and developer, I was curious to see how complicated would be to add the token to the wallet.
Feel free to close/reject the PR if this is not in line with the current dev roadmap.
---
No existing ticket.
This PR adds the new RHT token. See https://neotracker.io/asset/2328008e6f6c7bd157a342e789389eb034d9cbc4
I added the token to the token list.
I tested it manually compiling the app. I also run the test suite with `yarn test`. …
=> Add RHT token (Redeemable HashPuppy Token)

app/containers/Settings/Settings.jsx, app/core/schemas.js, app/modules/generateWallet.js
… recovery method
Does not fix any open issues
Application gets in an unusable state if an invalid JSON file is imported into wallet recovery in the Settings page. The code is assuming a String type for the account keys and does not handle some other types.
A basic schema approach to new accounts which checks for a valid type when setting keys. Instead of the current approach which accepts the import and then crashes on an Array.slice method if an incorrect type appears in the account.key it only accepts string key types and uses the Constructor to generate a new account object which has all of the relevant properties either passed through or defaults …
=>  FIX: application gets in bad state if incorrect json filed is used when restoring wallet

app/core/math.js, app/core/wallet.js, app/modules/sale.js
N/A
It replaces several remaining `parseFloat` calls to ensure we use BigNumber instead.
I reused our existing `toBigNumber` and `toNumber` calls.
I ran the test suite and sent transactions.  I did not test the sale changes since this is dependent on #528.
N/A
N/A
=> Replace parseFloat calls with BigNumber

__tests__/components/Inputs/AddressInput/__snapshots__/AddressInput.test.js.snap, app/components/Inputs/AddressInput/AddressInput.jsx, app/components/Inputs/AssetInput/AssetInput.jsx, app/components/Inputs/SelectInput/SelectInput.jsx
N/A
This fixes two issues in the token sale modal:
1. Typing into the token `SelectInput` did not filter token symbols as expected.
2. Pressing the backspace key in the `AssetInput` caused a JS error that made the page reload.
For the first problem, I fixed the `SelectInput` search to accept a custom `getSearchResults` prop that can search against `items` of any shape.  It was hardcoded to work against arrays of objects, but not arrays of strings.
For the second problem, I made the `AssetInput` maintain a search string in its component state, which gets reset on blur.  The `onChange` prop is only called if a valid asset it selected, rather than being …
=> Fixed token filtering & asset input bug in token sale modal

app/components/Modals/TokenSaleModal/SelectToken/index.jsx, app/components/Modals/TokenSaleModal/TokenSaleModal.jsx, app/core/math.js
This is a quick fix for a number of problems when trying to play with the numeric field for the token sale, it would die if you hit just '.', etc.
So, a number of checks were added to ensure that this is indeed a number before trying to parse it into bignumber.
Thanks @mhuggins for refactoring and contributing to this PR.
=> Fix number input

app/core/nep5.js, app/modules/transactions.js
This small fix allows the NEP5 transfer to use the decimals supplied by the SC.
=> Allow NEP5 transfer to use the SC decimals

app/modules/claim.js
#522 (among others)
Calculating claimable GAS can be off due to bad floating point math.
I replaced floating points with bignumber.js math.
Although this calculation is used for display only, I verified that claiming still works as expected.
I observed the redux store to ensure the calculation is correct.  I also claimed to ensure it works as expected.  (See screenshot below.)  The transaction in the blockchain confirms the correct amount was claimed: http://testnet.neoverse.io/transactions/1a7874a8158eaa84d4cb1180d4196e6d0c5ef450525358e0daa65bf745478f1b
**Are there any special changes in the code that we …
=> Fixed claimable GAS calculation

app/containers/Dashboard/Dashboard.jsx
N/A
With some recent changes I made to introduce new redux architecture, I accidentally broke the polling/refreshing on the dashboard when the user switches networks.  The polling function was fetching based upon an old network because the interval was not properly being cleared before setting a new one.
I checked to see if the function used for polling changed, and if it does, then clear the old poll before creating a new one.
Smoke tested.
N/A
N/A
=> Fixed refreshing dashboard data

app/actions/balancesActions.js
N/A
This fixes an issue where, if the user enters an invalid NEP-5 scriptHash in their settings, it gracefully loads the valid tokens without dying on the invalid ones.
I added a simply try/catch around the problematic code, allowing the valid responses to be returned and provided to the front-end wherever needed (e.g.: on the dashboard).
I smoke tested it with valid & invalid scriptHash values.
N/A
N/A
=> Added error handling when an invalid token scriptHash is entered

app/components/Modals/SendModal/SendModal.jsx, app/containers/Dashboard/index.js, app/core/wallet.js
N/A
This fixes a bug that I created when I introduced the accountActions as a batch action wrapper for balancesActions (among others).  When I replaced passing balance data into the component with account data, I failed to update the method signature to accept the new arguments.
I fixed the way arguments are received with regards to the balance data coming from that accountActions.
I smoke tested opening and using the send modal while inspecting the data being passed in.
N/A
N/A
=> Fixed passing token balances to send modal

app/actions/authActions.js
N/A
When I refactored the login actions, I neglected to set the signing function for ledger logins.  I wasn't able to test this since I don't have a ledger yet, but I happened to notice that it has no way of being set since it's not being passed in as an argument.  This should fix it.
I set the signing function to the function defined in the ledger module, which matches the way `master` branch sets the signing function.
I can't since I don't have a ledger.  Ledger login may be broken regardless of this change, someone needs to test it out on the `dev` branch.
**Are there any special changes in the code that …
=> Fixed signing function assignment for ledger login

app/actions/appActions.js, app/actions/priceHistoryActions.js, app/components/Dashboard/PriceHistoryPanel/AxisLabel.jsx, app/components/Dashboard/PriceHistoryPanel/BoundingBox.jsx, app/components/Dashboard/PriceHistoryPanel/BoundingBox.scss, app/components/Dashboard/PriceHistoryPanel/PriceHistoryChart.jsx, app/components/Dashboard/PriceHistoryPanel/PriceHistoryChart.scss, app/components/Dashboard/PriceHistoryPanel/PriceHistoryPanel.jsx, app/components/Dashboard/PriceHistoryPanel/PriceHistoryPanel.scss, app/components/Dashboard/PriceHistoryPanel/index.js, app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.jsx, app/components/Inputs/SelectInput/SelectInput.jsx, app/components/Panel/Panel.scss, app/containers/App/App.scss, app/containers/Dashboard/Dashboard.jsx, app/containers/Dashboard/Dashboard.scss, main.js, package.json, yarn.lock
N/A
This implements the NEO/GAS price chart based upon @asalib's designs.  (Proper fonts will be added in a follow-up PR.)
I added a new action set to fetch the data from cryptocompare.com's API, and I added the recharts package for rendering the chart in a new dashboard panel.  The user can toggle between NEO & GAS assets, as well as 1 month, 1 week, and 1 day timeframes.
I smoke tested it.  I'll be adding tests in a follow-up PR.
* New `recharts` package introduced.
* I increased the window width from 1000px to 1280px to match Alf's …
=> Added NEO/GAS price chart to dashboard

app/containers/WalletInfo/WalletInfo.jsx, app/core/constants.js
N/A
People have sent funds to ICO's that have ended, which caused them to lose money. This PR removes the ones that are known to have ended.
I have created a list of known ICO's that have ended, and that list is omitted from the tokens that are passed to the Sale Participation Modal.
Have tested it, both in MainNet/TestNet.
=> Omit ended ICO's

app/components/Modals/TokenSaleModal/ParticipationSuccess/index.jsx
N/A
When participating with just NEO, the participation success message also included GAS without any balance attached to it.
Zero balances/undefined balances are omitted now.
Tested participation with just NEO/GAS and both. Works well.
=> Omit balances with 0 or undefined for token sale participation success

app/containers/App/Sidebar/Sidebar.jsx, app/containers/App/Sidebar/Sidebar.scss
N/A
It moves the logout button to the bottom of the sidebar to match the designs.
*Before:*
*After:*
I used flexbox to align the sidebar sections.
Looked at the sidebar.
N/A
N/A
=> Updated logout button to display at bottom of sidebar

app/Root.jsx, app/index.js, config/webpack.config.dev.js
In the existing branch, hot reload is broken. Example: when logged into a wallet, viewing transactions history, adding a test div with text in it to `app/components/TransactionHistory/TransactionHistoryPanel/Transactions.jsx` and saving the file triggers a hot reload, but the reload never makes it past the initial app load loading animation screen. This makes it very difficult to see changes to the renderables, notably while implementing a redesign.
Resolves hot reloading issues. Changes to renderables are quickly reflected in the electron app while running in dev mode.
I initially asked @mhuggins to verify that hot reloading was not working. He …
=> Fix for hot reload issues

app/components/Modals/TokenSaleModal/SelectToken/index.jsx, app/components/Modals/TokenSaleModal/TokenSaleModal.jsx
Fixes #744
Copied from issue:
> An issue we ran into with a few of our contributors during our token sale is that they inadvertently sent both GAS and NEO when invoking mintTokens. If you first select GAS and enter an amount and then change to NEO and enter a new amount, the old value of GAS is still sent even though it's not present in the UI. This is an undesirable and unexpected side effect that users would not expect.
>
> It's probably best to limit ICO participation to either GAS or NEO? Alternatively, if some ICOs need to support both, the user experience should be improved to make it clear what's being sent, similar to the multi-recipient approach when sending funds in Neon wallet. …
=> Updated token sale behavior to clear previously selected asset amounts

app/containers/App/index.js
Fixes #796.
This resets the authenticated user's data when they logout from the wallet.  Without this, the next login during the same app session will end up displaying the previous account's data until the new data has loaded.
This is a temporary quick fix.  The issue is that calling `reset` on a batch action is not resulting in each associated action's `reset` function being called even though it should be.  (Specifically calling `reset` on accounts action should trigger `reset` for balances, claims, and transaction history.)
This fixes the issue for release.  I will circle back on a long term fix for batch resets.
**How did you make sure your solution …
=> Added short-term fix for resetting redux store keys on logout

app/modules/api/request.js
N/A
* If an action throws an error, it should clear the previously loaded data.
* If an action succeeds, it should clear the previous error message.
I updated the redux store for the current action when one of these scenarios occurs.
I visited the Ledger login screen and opened/closed the NEO app on it.  Previously, I saw both the success and error states on the login form.  Now I only see one or the other since the previous state is cleared.
N/A
N/A
=> Updated to clear stale redux state on action success or failure

app/containers/LoginLedgerNanoS/LoginLedgerNanoS.jsx
#798 point 3:
> 3: $Ledger $Nano
>
> Once you have opened the NEO app, you see:
> 
> > Found USB $Ledger $Nano S
> 
> as opposed to 0.1.4:
> 
> > Found USB Ledger Nano S
Removes leading $ signs from ledger device description.
Removed $ signs.
Smoke tested.
N/A
N/A
=> Fixed ledger device description to remove $ signs

__tests__/components/__snapshots__/TransactionHistory.test.js.snap, app/containers/TransactionHistory/index.js, app/sagas/batchSaga.js
N/A
This fixes a pretty significant issue that I noticed where we're duplicating all batched actions.  This resulted in duplicate API calls, duplicate local storage lookups, etc.  We haven't been using batch actions for updates, but if we had been, it would have updated data twice.
I removed the effective duplicate call.
I smoke tested the app, saw that requests are being made only once, and the app still behaves as expected.
The line removed and the one above it were having the same effect even though they were implemented …
=> Fixed duplicate API requests

app/actions/settingsActions.js
Fixes #797.
There was a bug that allowed users to inadvertently delete default tokens from local storage.  This would result in the hardcoded tokens no longer rendering token amounts (e.g.: RPX) despite the settings screen showing that the token exists there.
I updated the logic around fetching settings from local storage to ensure that the default tokens are always included in the list of user tokens.
I verified that both default tokens and custom tokens are now included in the redux store data and display on the dashboard as expected.
**Are there any special changes in the code that we should be aware …
=> Fixed issue with default tokens being deleted from local storage

__tests__/sagas/requestSaga.test.js, __tests__/util/api/createBatchActions.js, app/containers/App/index.js, app/sagas/batchSaga.js, app/sagas/index.js, app/sagas/requestSaga.js, app/util/api/createBatchActions.js
N/A
The basis of this change is to address a long-term fix for batch resets not working as expected.  This actually fixes related issues around resets and cancellations as well.  A short-term fix was implemented in #800, which this circles back on.
In addition, I cleaned up some differing logic between the action saga and batch saga to ensure they behave the same in similar scenarios.
I updated the saga matcher for batches to handle all 4 action types (requests, retries, resets, and cancellations), which then delegates to any child batch or child action.
I originally included a lot of console logging and …
=> Fixed retrying, resetting, and cancelling batch actions

app/actions/transactionHistoryActions.js
Fixes #813.
Load balancing was added in several spots recently, but load balancing the transaction history is not working due to a bug in neon-js.  Specifically, the neonDB and neoscan API's return different values, and the neoscan API sometimes returns bad data.
I reverted the load balancing of transaction history to only fetch from neonDB based upon @snowypowers advice:
> i went with the alternative implementation  as it would allow you to just iterate the balance object for easy retrieval of the amts
> anyway dont wait on this change, i want to add more tests to make sure both sides sync up properly. will probably take a day more
> on a side note, i …
=> Reverted load balancing change for transaction history

app/containers/WalletInfo/index.js
Fixes #746.
This hides any token balances of 0, since otherwise the list of tokens is overwhelmingly long for no reason.
I filtered out any tokens with a value of '0'.
Smoke tested and observed that only non-zero balances display.
N/A
N/A
=> Updated token list to hide zero balances

app/components/Modals/SendModal/AddRecipientDisplay.jsx
Fixes #746.
In my [previous PR](https://github.com/CityOfZion/neon-wallet/pull/815), I updated the token list on the dashboard to hide zero balances.  This updates the send modal to exclude tokens with a zero balance from the dropdown.  NEO & GAS are always available as options.
I checked the symbol to keep NEO & GAS and check the balance to keep any non-zero amount.
Opened the send modal for various addresses that don't have NEO/GAS or only have 1-2 types of tokens.
N/A
N/A
=> Hide zero-balance tokens in send modal

app/actions/pricesActions.js, app/components/Dashboard/PortfolioPanel/PortfolioBreakdownChart.jsx, app/components/Dashboard/PortfolioPanel/PortfolioBreakdownChart.scss, app/components/Dashboard/PortfolioPanel/PortfolioPanel.jsx, app/components/Dashboard/PortfolioPanel/PortfolioPanel.scss, app/components/Dashboard/PortfolioPanel/PortfolioRow.jsx, app/components/Dashboard/PortfolioPanel/PortfolioRow.scss, app/components/Dashboard/PortfolioPanel/PortfolioTable.jsx, app/components/Dashboard/PortfolioPanel/PortfolioTable.scss, app/components/Dashboard/PortfolioPanel/colors.js, app/components/Dashboard/PortfolioPanel/index.js, app/components/Dashboard/TokenBalancesPanel/index.js, app/containers/Dashboard/Dashboard.jsx, app/containers/Dashboard/Dashboard.scss
N/A
This implements the new portfolio design into the v2 dashboard.  It also filters out zero-balance assets/tokens from both the token balances panel and the portfolio panel.
* Added new panel component for portfolio panel
* Added portfolio chart component for donut
* Added portfolio table component
* Updated `pricesActions` to fetch full mapping of tokens to currency price.
Smoke tested it, compared the value & percentage calculations manually.
N/A
N/A
=> Added portfolio panel to new dashboard

__tests__/components/Claim.test.js, __tests__/components/__snapshots__/Claim.test.js.snap, app/containers/Claim/Claim.jsx, app/containers/Claim/index.js, app/modules/claim.js, app/util/delay.js, app/util/poll.js
Pretty much all the GitHub issues around claiming GAS.
This PR ensures that, when claiming GAS, we perform two actions and wait for them to complete:
* send all NEO to the current address
* poll to wait for updated list of claims for the current address
Note that these two actions only occur if the NEO balance > 0.  Otherwise, GAS claim immediately occurs.
I refactored the behavior between the claim component and the claim module.  Rather than the component trying to manage the entire claim request lifecycle, it instead just kicks off the claim when the user click's the claim button.  The module now manages the entire lifecycle, which includes the steps …
=> Updated to poll for new claims before claiming GAS

app/actions/balancesActions.js
N/A
Sometimes when we get an API response back for asset balances, it *only* includes a GAS key *or* a NEO key; not both.  In such circumstances, we can assume the balance is '0'.  Without this change, an error is raised, and the app just shows a white screen.
I short-circuited to return '0' for either asset balance if the key is not set.
Logged into an account that has only ever had GAS and no NEO.
N/A
@snowypowers This might be worth fixing on the neon-js side of things.
=> Fixed issue with missing asset key in balances response

__tests__/modules/metadata.test.js, app/modules/metadata.js, package.json, yarn.lock
N/A
This changes the behavior for the "your wallet is out of date" notification to only display the notification if the version is older than the latest version.  This will ensure that wallets with a *newer* version than we track in the neon DB do not see the notification, which has historically confused users.
I added the [`compare-versions` package](https://www.npmjs.com/package/compare-versions) and used it to compare the currently installed package version to the latest available version.
I added tests!
N/A
**Is there anything else …
=> Updated version comparison to only notify for older versions

app/modules/claim.js
#832
This restores some of the additional messaging for the Ledger and non-Ledger flows:
* Ledger users see "1 of 2" and "2 of 2" in the signing notifications, better guiding through the cliam process.
* Non-Ledger users will now see an initial notification when claiming starts.  Without this, the user is only informed *after* claiming has succeeded, which can take upwards of 30 seconds easily.
I added some dispatched notifications that were lost during a previous fix around this feature.
I claimed GAS with & without a Ledger.
N/A
**Is …
=> Restored claiming gas messaging for clarity

__mocks__/neon-js.js, __tests__/actions/authActions.test.js, app/actions/authActions.js
N/A
Users are currently able to login with their address or public key instead of WIF or private key.  Nothing can actually be done other than looking at publicly accessible data, but we should not incorrectly authenticate in the first place.
I tested that the string provided to the authentication function is a WIF or private key.
I smoke tested and added tests.
N/A
N/A
=> Fixed private key login to only permit private key or WIF

__tests__/components/App.test.js, app/actions/appActions.js, app/containers/App/index.js
Fixed #843.
The price functionality always reflects the USD value even if you change it to any other currency.  The symbol changes, but the number doesn't.  For example, you might see 1 NEO at 95 USD and also at 95 JPY.
I separated the call for prices data to occur after settings data have been loaded.  This is necessary since we don't know the user's desired currency until settings are loaded, and the currency is needed to make the token prices fetch request.
I loaded up the dashboard with the currency set to USD and not USD, confirming that it shows not just different symbols but also different/correct …
=> Fixed balance calculation for non-USD currencies

package.json, yarn.lock
This is a simpler upgrade that fixes the sales problem without destroying the test suite.
=> Upgrade neon-js to 3.3.3

__tests__/sagas/requestSaga.test.js, app/hocs/withFailureNotification.js, app/sagas/requestSaga.js
N/A
When authenticating with private key or WIF, if the user encounters we show an error notification.  If the user encounters a second error (or more), we do not show another error notification even though we should.
Without this change, the initial failing request would have the redux state change from "LOADING" to "FAILED".  Subsequent requests would simply remain at the "FAILED" state.
I added a delay to the redux saga request to ensure that the redux store has a chance to cycle through all state changes.  It now properly reflects a change from "FAILED" to "LOADING" and back to "FAILED" again if the request does not succeed.
**How did you make sure …
=> Fixed repeat error notifications not appearing

app/modules/transactions.js
Currently, without any reporting system in place, it is impossible for us to judge what is the problem because the only thing the users can tell us is `Transaction Failed`. This PR attempts to surface the errors by printing the error message if the transaction actually fails before even getting sent. 
This way, we are able to debug with more information available because these errors are more likely to be code issues than network issues.
This is an example:
=> Surface errors from tx failures

app/modules/generateWallet.js
Fixes Issue #776
Prevents users from creating multiple wallets with the same label/alias, which implicitly fixes the wallet deletion bug described in issue #776.
Checked for a duplicate label in the saveAccount() method in app/modules/generateWallet
It was straightforward to test. When a user attempts to create another wallet with the same label, an error message is flashed on the Electron app telling them to choose a different name.
=> Prevented multiple wallets from having the same label (fixes #776)

app/containers/App/Footer/Footer.jsx
Resolves issue #880 
It adds a direct invite link to the discord support server 
Added the discord link to the footer JSX template and made it open the link in an external browser on click
Tested the link on my local computer and verified that it works as intended
=> Added Discord invite link to footer (fixes #880)

.circleci/config.yml
None.
Fixed failing e2e tests.
Added display server related packages for Chrome Driver.
Ran tests on my private CircleCI:
https://circleci.com/gh/drptbl/neon-wallet/11
Nope.
Nope.
=> Fixed failing e2e tests because of missing Chrome Driver dependencies

__e2e__/create-new-wallet.e2e.js, package.json
Tried to keep it as simple as possible. I think that other checks should be done in separate test cases.
I've also added `-s` (running tests serially) to `test:e2e` script based on https://github.com/avajs/ava/issues/1060 to prevent flakiness and limit electron instances while running tests.
Let me know if there's anything to change/improve.
Feedback is very welcome.
=> Add e2e tests for creating new wallet and run tests serially

.circleci/config.yml
This adds the ability to use CI to build upon tagging. I have it setup for linux and windows builds.
1. We will have to tag the build beforehand. Instead of using the release page to tag, we use cmd. Assuming we are on `master` on the commit that we want to release:
```
git tag 0.2.3
git push upstream 0.2.3 --no-verify
```
This will push the tag up and CircleCi should pick this up and trigger the builds.
The builds can be found by going to Workflows -> neon-wallet. The dist folder is uploaded as artifacts. Unfortunately, I do not see anyway to automate the attachement of the builds to the release draft so we will have to do this ourselves.
=> feat(ci): automated builds upon tagging

app/Root/Root.jsx, app/Root/index.js, app/components/Modals/SendModal/SendModal.jsx, app/core/wallet.js, app/index.js, config/webpack.config.dev.js, package.json, webpack.config.js, yarn.lock
N/A
This fixes issues with trying to use the `async`/`await` keywords in react component functions, which was not supported in react-hot-loader v3.  (More details can be found [here](https://github.com/gaearon/react-hot-loader/issues/391#issuecomment-353867009).) It also updates the new blacklist check to use `async` instead of `promise.then`.
I upgraded react-hot-loader to v4 and updated a react component function to use `async`.  `react-hot-loader` updates are based upon the documentation found [here](https://www.npmjs.com/package/react-hot-loader#migrating-from-v3).
I smoke tested sending NEO to …
=> Fixed autobind for async/await in react components

__tests__/actions/authActions.test.js, __tests__/actions/claimsActions.test.js
N/A
Some `.only()` calls were accidentally left in tests, which prevents the full suite from running.
I removed the `.only()` calls.
Ran the test suite.
N/A
N/A
=> Removed unintentionally left .only() calls in tests

app/core/constants.js
N/A
This removes ONT and SWH tokens from displaying in the token sale modal since their token sales are over or never occurred.
Added both token symbols to the array used for tracking completed ICOs.
Opens the token sale modal and confirmed they're not available in the dropdown.
N/A
N/A
=> Removed more tokens that have completed ICOs

app/components/Modals/TokenSaleModal/TokenSaleModal.jsx, app/components/Modals/TokenSaleModal/WarningText/index.jsx
N/A
Many users are blindly sending NEO/GAS for already completed token sales.  Providing a gigantic red block of warning text that takes up half the screen apparently isn't enough to deter many users from using the feature without understanding it.  This changes the warning text to be distinct checkboxes that the user must agree to in order to draw better attention to what it says.
I updated the warning text to be 5 distinct checkboxes that must be clicked before the form can be submitted.
I verified that the button is disabled when any of the 5 checkboxes is not checked, as well is when any other validation …
=> Updated token sale screen to require user to manually agree to purchase terms

app/actions/accountsActions.js, app/containers/App/App.jsx, app/containers/App/index.js, app/containers/CreateWallet/CreateWallet.jsx, app/containers/DisplayWalletAccounts/index.js, app/hocs/helpers/everLoadedStrategy.js, app/hocs/withFailureNotification.js, app/hocs/withSuccessNotification.js, app/modules/generateWallet.js
Fixes #850.
Fixes #852.
This addresses two issues related to account management:
* Creating a new account does not display it in the settings screen until app is restarted.
* Deleting a saved accounts results in a blank white page / requires app restart.
I moved one of the old thunk-based reducers to use the newer redux action architecture.  Without this, reducers related to account management was not aware of actions being handled by separate reducers.
I smoke tested account creation via the different mechanism along with account deletion.
**Are there any special changes in the code that we should be aware …
=> Fixed new accounts not displaying in settings & account deletion causing white screen

__tests__/components/__snapshots__/WalletInfo.test.js.snap, app/components/Modals/TokenSaleModal/ParticipationSuccess/index.jsx, app/components/Modals/TokenSaleModal/SelectToken/index.jsx, app/components/Modals/TokenSaleModal/SelectToken/styles.scss, app/components/Modals/TokenSaleModal/TokenSaleModal.jsx, app/containers/WalletInfo/WalletInfo.jsx, app/containers/WalletInfo/index.js, app/core/constants.js
N/A
Users are blindly selecting tokens from the token sale modal and sending NEO/GAS after token sales end without understanding what they're doing.  This will prevent them from easily participating.  Instead, they will have to enter a valid script hash.
I replaced the asset dropdown with a script hash input field.  A lot of cleanup was also possible because there is no longer a need to look up a token based upon its symbol.
* I successfully purchased THOR via script hash on TestNet at a verified address.
* I unsuccessfully purchased QLC via script hash on TestNet using an unverified address.
* I …
=> Mint script hash

__tests__/components/__snapshots__/WalletInfo.test.js.snap, app/components/Modals/TokenSaleModal/ParticipationSuccess/index.jsx, app/components/Modals/TokenSaleModal/SelectToken/index.jsx, app/components/Modals/TokenSaleModal/SelectToken/styles.scss, app/components/Modals/TokenSaleModal/TokenSaleModal.jsx, app/containers/WalletInfo/WalletInfo.jsx, app/containers/WalletInfo/index.js, app/core/constants.js
Reverts CityOfZion/neon-wallet#931
After following up @Ejhfast, his preference is to restore the token dropdown given that we're working towards implementing a `token.json` file that we can fetch in the near future.  This removes the script hash input and brings that dropdown back.
=> Revert "Replace token sale asset dropdown with script hash input"

app/components/Modals/TokenSaleModal/ConfirmToken/ConfirmToken.jsx, app/components/Modals/TokenSaleModal/ConfirmToken/ConfirmToken.scss, app/components/Modals/TokenSaleModal/ConfirmToken/Failed/Failed.jsx, app/components/Modals/TokenSaleModal/ConfirmToken/Failed/Failed.scss, app/components/Modals/TokenSaleModal/ConfirmToken/Failed/index.js, app/components/Modals/TokenSaleModal/ConfirmToken/Loading/Loading.jsx, app/components/Modals/TokenSaleModal/ConfirmToken/Loading/Loading.scss, app/components/Modals/TokenSaleModal/ConfirmToken/Loading/index.js, app/components/Modals/TokenSaleModal/ConfirmToken/index.js, app/components/Modals/TokenSaleModal/ParticipationSuccess/index.jsx, app/components/Modals/TokenSaleModal/ParticipationSuccess/styles.scss, app/components/Modals/TokenSaleModal/SelectToken/index.jsx, app/components/Modals/TokenSaleModal/TokenSaleModal.jsx, app/util/toSentence.js
N/A
This adds the token verification screen.  I originally approached this as part of #932, but I closed that and refactored due to a change in direction from Ethan in terms of how we should approach the token sale window.
This extra step will help to ensure users re-read what they're sending, where they're sending it, etc. before actually confirming.
I added an extra step to the token sale modal.  It's now a 3 step process.
I smoke tested with various tokens and addresses and amounts.  The attempts that should have succeeded did, and the attempts that should have failed did.
**Are there any special changes …
=> Added token sale verification screen

app/containers/App/Footer.jsx
Fixes #980.
Clicking the "Community Support" link in the footer opens the link, but it also navigates the user back to the login screen.
I called `event.preventDefault()` to not have the link be handled by react-router.
Clicked the link.
N/A
N/A
=> Fixed community support link in footer

app/components/Button/Button.scss, app/components/Contacts/AddContactPanel/AddContactPanel.jsx, app/components/Contacts/AddContactPanel/AddContactPanel.scss, app/components/Contacts/AddContactPanel/index.js, app/components/Contacts/ContactForm/ContactForm.jsx, app/components/Contacts/ContactForm/ContactForm.scss, app/components/Contacts/ContactForm/index.js, app/components/Contacts/ContactsPanel/ContactsPanel.jsx, app/components/Contacts/ContactsPanel/ContactsPanel.scss, app/components/Contacts/ContactsPanel/index.js, app/components/Contacts/EditContactPanel/EditContactPanel.jsx, app/components/Contacts/EditContactPanel/EditContactPanel.scss, app/components/Contacts/EditContactPanel/index.js, app/components/Root/Routes.jsx, app/containers/AddContact/AddContact.jsx, app/containers/AddContact/AddContact.scss, app/containers/AddContact/index.js, app/containers/App/Sidebar/Sidebar.jsx, app/containers/Contacts/Contacts.jsx, app/containers/Contacts/Contacts.scss, app/containers/Contacts/index.js, app/containers/EditContact/EditContact.jsx, app/containers/EditContact/EditContact.scss, app/containers/EditContact/index.js, app/core/constants.js, app/modules/addressBook.js
Most of #972.
This implements the v2 designs around contacts:
* Contacts link in sidebar navigation.
* Contacts list screen.
* Add contact screen & functionality.
* Edit contact screen & functionality.
* Delete contact functionality.
I added 3 new routes for the contacts list, add contact, and edit contact pages.  These pages are under the `containers` folder, while each of the associated components are in the `components` folder.
I managed my own contacts list!
N/A
There is still one known …
=> Added v2 design for contacts

main.js
#1012
It solves an issue while dev tools can't be opened on Windows or Linux machines.
Added an ability to open dev tools using "F12" hotkey.
I've tested it on Linux and Windows machine manually by running the wallet and checking if dev tools are opening properly after pressing "F12" hotkey while window is active and if they don't open while window is deactivated.
I don't think so.
Nope.
=> Open DevTools with "F12" hotkey while on Windows/Linux machine

__tests__/components/Dashboard/__snapshots__/AssetBalancesPanel.test.js.snap, app/components/Dashboard/AssetBalancesPanel/AssetBalancesPanel.jsx, app/components/Dashboard/AssetBalancesPanel/AssetBalancesPanel.scss, app/components/Dashboard/AssetBalancesPanel/index.js, app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.jsx, app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.scss, app/components/Dashboard/TokenBalancesPanel/index.js, app/hocs/withLoadingProp.js, app/styles/animations.scss
Fixes #994.
There is currently no feedback on the refresh buttons in the v2 dashboard, making it impossible to tell that anything is happening.  This adds a spin animation to those buttons while loading.
I added a CSS animation to the refresh icon, which only spins when the progress is in a loading state.
I used the refresh button.
N/A
N/A
=> Added loading animation to refresh icon on v2 dashboard

__mocks__/svgMock.js, __tests__/components/Dashboard/AssetBalancesPanel.test.js, __tests__/components/LoginNep2.test.js, __tests__/components/TransactionHistoryPanel.test.js, __tests__/components/__snapshots__/Claim.test.js.snap, __tests__/components/__snapshots__/Logout.test.js.snap, app/containers/Claim/Claim.jsx, package.json
Fixes #990.
The v2 claim button was missing its icon and had the wrong colors.  We also were not properly mocking SVG's for use in jest.
I updated the button properties.  I added a new mock file used for SVG's to treat them as components.  I also fixed the way we're identifying ID'd components in tests by replacing `first` with `hostNodes`.
Viewed the button, ran the tests.
N/A
N/A
=> Fixed claim button styling

__tests__/core/explorer.test.js, app/core/constants.js, app/core/explorer.js
Fixes #1026.
This removes NEOverse from the list of block explorers.
I removed the constants as well as conditionals referencing the constants.
Checked the settings screen & clicked a link for a transaction.
N/A
N/A
=> Removed NEOverse from list of explorers

app/actions/transactionHistoryActions.js, flow-typed/declarations.js, package.json, yarn.lock
Fixes #1028.
Fixed #1039.
* Some RPC servers are at the current block height, but they are unresponsive.  The latest version of neon-js helps to prevent those servers from being used.
* Claimable GAS calculation is returning 0 for some users.
I upgraded neon-js to 3.7.0, which fixes both issues.
I tried performing various RPC related actions, logging in & out (which fetches balances via RPC), and everything has been working for me.
N/A
This can't be merged until neon-js 3.7.0 is released. …
=> Updated neon-js to 3.7.0

app/core/constants.js
N/A
Removes EFX, THOR, and CGE from token sale screen.
I added them to the `ENDED_ICO_TOKENS` constant.
Ensure they don't show up in the dropdown.
N/A
N/A
=> Removed EFX, THOR, and CGE from token sale screen

yarn.lock
N/A
This attempts to fix the build failure as seen here: https://circleci.com/gh/CityOfZion/neon-wallet/1943
I upgraded the deep `upath` dependency.
I pushed it to Github & let Circle build.
N/A
N/A
=> Fixed CI build by upgrading upath dependency

app/components/Modals/SendModal/AddRecipientDisplay.jsx, app/components/Modals/SendModal/AddRecipientDisplay.scss, app/modules/transactions.js
N/A
This removes the "1 drop of GAS" requirement for transferring NEP5 tokens.  Now that we're using the latest version of neon-js, transfers don't need to include an intent for sending 0.00000001 drop of GAS.  Instead, an attribute is used behind the scenes.
I removed the intent for sending 0.00000001 GAS to the currently authenticated account.  I also removed any messaging related to it.
I transfered NEP5 tokens.
N/A
N/A
=> Removed drop of GAS requirement for transfers

__tests__/components/__snapshots__/LoginNep2.test.js.snap, app/actions/authActions.js, app/containers/Home/Home.jsx, app/containers/Home/index.js, app/containers/LoginLocalStorage/LoginLocalStorage.jsx, app/containers/LoginLocalStorage/index.js, app/containers/LoginNep2/LoginNep2.jsx, app/containers/LoginNep2/index.js, app/hocs/withLoadingProp.js
N/A
This updates the NEP2 login action perform asynchronously.
I updated the NEP authentication action to use `decryptAsync` instead of `decrypt`.  This prevents the app from seemingly hanging while authenticated.  Since the user can continue to interact with the app with this change, it was also necessary to add loading state & disable fields while decrypting.
I tested all forms of login.  I also tried interacting with form elements and buttons/links on the screen while decrypting.
N/A
N/A
=> Updated NEP2 login to decrypt asynchronous & show loading state

app/components/Dashboard/PortfolioPanel/PortfolioRow.scss
None
Currently flex styles in the PortfolioRow component do not actually do anything due to percentage widths being applied. Relying on flex will allow easier customisation of ratios in the future.
Remove `width: 50%` and `width: 100%` styles and instead rely on `flex-grow`.
I've tested on macOS that the behaviour when resizing is the same as before.
`flex-basis` changed from auto to 0 to keep the same behaviour as before when using `width`.
I originally wanted to take a look at …
=> Fix PortfolioRow flex

app/core/constants.js
N/A
It adds IAM and PKC from the list of ended token ICOs.
Added the token symbols to the constant that tracks ended ICOs.
Ensure they don't appear in the token sale modal dropdown.
N/A
N/A
=> Removed IAM and PKC from ICO tokens list

app/containers/DisplayWalletAccounts/DisplayWalletAccounts.jsx
N/A
The tooltips for copying aspects of a new wallet all read "Copy Passphrase".
I updated the tooltips to use the correct label to match the item being copied.
I hovered over each copy icon to ensure the tooltip is correct.
N/A
N/A
=> Fixed copy tooltips

__tests__/components/__snapshots__/TransactionHistory.test.js.snap, app/actions/transactionHistoryActions.js, app/containers/TransactionHistory/index.js
N/A
This changes the transaction history fetch to get the latest page of transactions from neoscan rather than the full history.  It also updates the transaction history sidebar to gracefully fail if the fetch does not succeed, preventing the white screen of death.
I replaced the neon-js call with a raw axios call.
I smoke tested several addresses and compared the results to neoscan.
N/A
@snowypowers In case you want to mimic this behavior in neon-js, this is what I did.
=> Updated transaction API fetches to use paginated neoscan endpoint

app/actions/pricesActions.js, app/containers/App/Header/Header.jsx, app/containers/App/Header/PriceDisplay/PriceDisplay.jsx, app/containers/App/Header/index.js, app/containers/WalletInfo/WalletInfo.jsx, app/containers/WalletInfo/index.js, flow-typed/declarations.js
https://github.com/CityOfZion/neon-wallet/issues/1122
When CMC is down the dashboard will turn blank.
Using lodash `get` when getting the prices, and also made a new `Prices` type, and marked all prices as optionals.
In addition to that, I also replaced the `neoValue/gasValue` calculations to use BigNumber.
Tested it with cmc with null/undefined/bad values
No.
No.
No.
=> fix(dashboard): Allow dashboard to load despite having bad cmc response

__tests__/components/App.test.js, __tests__/components/__snapshots__/App.test.js.snap
N/A
Since the `dev` branch was last merged into `design-v2`, the App container test started failing.  This is due to discrepancies in ordering of data loading.
I've updated the test to compare snapshots for changes rather than checking for data loading since that has changed.
Ran `yarn test`.
N/A
N/A
=> Fixed App container tests

app/components/Contacts/AddContactPanel/AddContactPanel.jsx
Fixes #1145.
The new contact form button was labeled "Save Contact" instead of "Add to Contacts".
I passed a prop to apply the correct button label.
I navigated to the add & edit contact screens to ensure each displays the correct label.
N/A
N/A
=> Fixed save contact button label

app/actions/appActions.js, app/containers/App/Header/WalletBlockHeight/WalletBlockHeight.jsx, app/containers/App/Header/WalletBlockHeight/index.js
https://github.com/CityOfZion/neon-wallet/issues/1128
This PR solves the infinite loader that shows when block height action fails on initial wallet load.
I moved blockHeight actions from the batched app actions to WalletBlockHeight component. The batched app actions should only be for critical stuff, because if one of them fails, then the wallet won't load. It is much safer, and performant to move it to the consumer of the data, which is the WalletBlockHeight.
Saw that the block height shows correct numbers for MainNet/TestNet, and that it shows a dash '-' when its undefined/null.
**Are there any special …
=> Move blockHeight action into WalletBlockHeight component

app/components/Contacts/ContactsPanel/ContactsPanel.scss
Fixes #1141.
Fixes #1142.
The contacts screen's "Edit" and "Delete" buttons were too narrow, and the pencil icon in the "Edit" button was being clipped.
I made the buttons wider, which also fixed the icon clipping.
Viewed the screen.
N/A
N/A
=> Fixed contact button sizes & icon clipping

__tests__/actions/blockHeightActions.test.js, app/actions/blockHeightActions.js
Fixes #1127.
This replaces the API call for the current block height with an RPC call.
I update the `blockHeightActions` file to use RPC for getting the current block height.
I logged into an account and ensured the block height displayed in the header.
N/A
N/A
=> Updated to fetch block height from RPC

__e2e__/view-balance.e2e.js
N/A
The end-to-end test for checking transaction history has not been working as expected.  This was unknown because neoscan TestNet had been down for awhile.  Now that it's working, we can see that this test is failing.
I updated the test to not care about transaction ID ordering.
I ran the test suite.
N/A
N/A
=> Fixed e2e test for transaction history

app/containers/DisplayWalletAccounts/DisplayWalletAccounts.jsx, app/styles/main.global.scss
- QR code for the private key is missing
- The subtitle of the QR code for the encrypted key is possibly confusing to new users.
- Added a third QR code for the private key.
- Updated the subtitle on the QR code for the encrypted key to match the value that was provided below. 
As far as security is concerned, the private key is already provided in this screen, so adding the QR code for it's value does not reveal any additional information that is not already present.
Since the names will now match between the each of the 3 QR codes and the values provided below them, it will make it more clear for users.
Current
Updated
*These are random values from newly created wallets
=> Update new wallet information qrcodes

app/components/Dashboard/PortfolioPanel/PortfolioBreakdownChart.jsx, app/components/Dashboard/PortfolioPanel/PortfolioPanel.scss
Issue #1006 
The portfolio pie chart had padding of its own. When combined with the padding of its parent container, there was too much whitespace between the edge of the portfolio panel and the chart.
Cutting down on the whitespace between the edge of the portfolio panel and pie chart to match the design documents as well as other elements on the page.
See for yourself!
Before:
After:
This is probably nothing, but I used a negative margin value (margin-top: -25px), which is kind of hokey, but unfortunately, it was the only elegant …
=> Fixed spacing on portfolio pie chart to match design notes (fixes #1006)

app/components/Dashboard/PriceHistoryPanel/index.js
Issue #1100 
Currently, clicking on the "duration" tab in the wallet dashboard throws a js error
In all places other than the priceHistory panel, Spunky's ```withActions``` is passed a JSON object of one-line lambda functions. In these instances, the result of the ```actions.call``` line was implicitly passed back to the ```withActions``` function. However, since ```getDurations``` was multiple lines, the final line of the function needed to be explicitly returned in order for ```withActions``` to properly map new functions onto the props object.
I clicked the duration button and the asset button a few times …
=> Fixed duration button on price history graph (fixes #1100)

app/components/Dashboard/AssetBalancesPanel/index.js
Network, auth, and token data were not being imported into assetBalances. Because of this, the GET requests for refreshing asset balances were being treated as absolute paths on the filesystem (such as localhost/undefined/.../undefined/). This was because information necessary for the network path was not being injected into props. By correctly injecting ```net```, ```address```, and ```tokens``` into the component's properties, proper requests to retrieve asset balances can be formed.
Issue #1079 (and possibly #1080)
The asset balances component crashed the wallet when you clicked refresh. Before refresh was clicked, data was not being populated into the correct component.
**How did you …
=> Fixed balances endpoint address (fixes #1079)

app/index.js, app/styles/main.global.scss, package.json, yarn.lock
Issue #1007 
The font being used before didn't match the design notes 
I imported ```typeface-montserrat``` and set it as the default font-family
I verified that all elements used the new font
I added Montserrat to the list of package dependencies
=> Changed font to Montserrat (fixes #1007)

app/components/Dashboard/PortfolioPanel/PortfolioPanel.scss, app/styles/main.global.scss
Issue #1006 
Some text was rendering as 10px  because I messed up the default font size in my font rule. Also, the portfolio chart wasn't being vertically centered correctly, so I fixed that as well.
Misc. CSS fixes. See code
I visually verified various tabs looked correct
=> CSS Fixes for portfolio chart spacing and default font size (fixes #1006 again)

app/containers/DisplayWalletAccounts/DisplayWalletAccounts.scss
Issue #1146 
There wasn't enough spacing to the right of created wallet information labels
I increased the label container's width by 20px
I verified visually
=> Fixed 'Create Wallet' spacking (fixes #1146)

app/hocs/withProgressPanel.js
Issue #1080 
Currently, when you click the "retry" button, spunky automatically loads up the previous state of the panel and shows it until axios fails to grab necessary information. This causes the previous working state of a panel to sometimes pop up for a fraction of a second when you click the "retry" button.
By switching to the "recentlyCompleted" in the load cycle, spunky now assumes the following: If a panel is currently in the "FAILED" state, it will most likely fail again. This prevents the previous state from flashing onto the screen while still keeping the normal refresh button behavior the same.  …
=> Fixed panel flickering on retry button (fixes #1080)

__tests__/components/__snapshots__/LoginNep2.test.js.snap, app/actions/accountsActions.js, app/actions/authActions.js, app/containers/LoginNep2/LoginNep2.jsx, app/containers/LoginNep2/index.js, app/core/account.js, app/styles/login.scss
Users who have have a encrypted key that was not created in neon-wallet or imported via JSON, need to have an easy option to allow them to save their account when logging in.
Added an options to set a account name, and save the account upon logging in.
- Naivigate to "Login using an encrypted key"
- Enter passphrase and encrypted key
- Check the option for save account
- Enter a account label
- Login
- If successful, you will be taken to the normal account dashbaord
Corner cases
- If the user already saved this encrypted key, it will simply ignore the new label, and log in the user
- If the user enters a label that is conflicting with one that is already saved, it will …
=> Add option to save account NEP2 login screen

app/actions/authActions.js, app/components/Modals/EncryptedLoginModal/EncryptedLoginModal.jsx, app/components/Modals/EncryptedLoginModal/EncryptedLoginModal.scss, app/components/Modals/EncryptedLoginModal/index.js, app/components/PasswordField/PasswordField.scss, app/containers/DisplayWalletAccounts/DisplayWalletAccounts.jsx, app/containers/DisplayWalletAccounts/index.js, app/containers/ModalRenderer/ModalRenderer.jsx, app/containers/Settings/Settings.jsx, app/containers/Settings/index.js, app/core/constants.js, app/modules/generateWallet.js, app/styles/main.global.scss
Currently there is no way for users who have created their wallets with neon-wallet to recall the credentials screen that was displayed when they first created the wallet. While it could be argued that it is for their own security that they not be able to pull up this information again, and that it's their responsibility to save these details upon creation. However, the sad reality is that there are many people who save their wallet, and blow past this screen without a second thought. While users are able to export their wallet recovery JSON file with their encrypted key, many less technical people have no idea what this file is or how to make sense of it.
In order to remedy this, an option was added to the wallet …
=> Add ability to recall saved wallet address credentials

__tests__/core/explorer.test.js, app/core/explorer.js, app/core/explorerConfig.js
N/A
The URL format for antchain explorer has changed, which means links to transactions are broken in the wallet.
Adjusted the URL format, and reworked the code for handling URLs to be more generic. I will get explorer.js to 100% coverage in another PR.
Tested that updated links worked now.
There was a general refactor of how the explorer links are generated and how the data is stored.
N/A
=> Fix explorer links

app/components/Root/Routes.jsx, app/containers/CreateWallet/CreateWallet.jsx, app/containers/DisplayWalletAccounts/DisplayWalletAccounts.scss, app/containers/Home/Home.scss, app/containers/Home/HomeLayout.jsx, yarn.lock
https://github.com/CityOfZion/neon-wallet/issues/1271
https://github.com/CityOfZion/neon-wallet/issues/1275
https://github.com/CityOfZion/neon-wallet/issues/1272
https://github.com/CityOfZion/neon-wallet/issues/1277
https://github.com/CityOfZion/neon-wallet/issues/1278
When I rewrote the import and create functionality I forgot to pass `history` down as a prop... this broke import and create functionality. This PR fixes that bug.
This PR also adjusts styles in the home container and logo display in Create and Import.
**Is there …
=> fixes import and create functionality as well as design tweaks

package.json, yarn.lock
#1286 
Switch to `statetx` branch so we can use the voting methods.
=> switch to statetx branch for neon-js

__tests__/modules/metadata.test.js, app/modules/metadata.js
https://github.com/CityOfZion/neon-wallet/issues/1298
By using github instead.
Manually testing locally... automated tests coming soon
=> fixes request to version check

app/components/Dashboard/TokenBalancesPanel/index.js
#1232 
Order matters in recompose's `compose` function. In this case, calling `withProgressPanel` after `withNetworkData` was nuking the props needed in `balancesActions`. I did not go down the rabbit hole of figuring out why this worked when an internet connection was present.
I moved `withNetworkData` before `withProgressPanel`. For consistency's sake I moved a few others to more closely align with the export defined in `AssetBalancesPanel/index.js`.
Manually tested. See proper host called in screenshot below.
No.
**Is there anything …
=> Fixes token balances section calls wrong path [#1232]

app/modules/generateWallet.js
#1276
Improves the default error message for the "import" and "generate" wallet screens.
Added a ternary that switches based on the argument passed in for importing new wallets.
Manually tested.
=> Update error message based on import or generate wallet

app/index.js
Although no associated issue Im sure this drives anyone contributing to neon-wallet a little crazy as HMR was not configured properly. This PR resolves the issue please see gif below.
WITH THESE CHANGES:
WITHOUT:
This will speed up engineering time substantially! Currently every time a change is made developer has to reauthenticate - very painful.
By reading through the documentaion
=> fixes hot reloading in dev mode

app/actions/settingsActions.js, app/containers/App/App.jsx, app/containers/App/App.scss, app/containers/Settings/Settings.jsx, app/containers/Settings/index.js, app/core/constants.js, app/hocs/withThemeData.js, app/styles/main.global.scss, app/styles/variables.scss, app/themes/Dark.js, app/themes/Light.js, app/themes/index.js
Hi all,
I've completed a few bug fixes already in this repo, but this is my first PR for a feature. I tried to closely follow the design patterns already in place, but speak up if not.
This PR specifically addresses the implementation of a system for toggling between themes. It does so by swapping Sass variables for native CSS variables wherever dynamic colors are required. The theme is passed in once at the root level and the variable definitions cascade down through the other components. There are a number of ways this could be done, but I think this route is pretty clean as it didn't require major changes to the way styles are implemented in the app. New themes are also VERY easy to add as they are just a simple object.
Swapping the remaining variables and defining the actual color …
=> Add theme handler

app/core/explorer.js, package.json, yarn.lock
None/ Discussed this with @comountainclimber in discord chat
Broken URL when clicking on addresses (on receive tab your own address for example)
`addressLinkStructure` was written incorrectly
Tested it manually
Nope
nope
=> chore(explorer): fixed broken link for addresses

app/containers/Send/index.js
https://github.com/CityOfZion/neon-wallet/issues/1081
This PR fixes a bug causing the application to crash if balances were unavailable (offline mode or clicking send before data was loaded)
By wrapping conditionals around the null values
Testing locally in offline and online modes
I reached out to design but we need to update this ugly default state of having no balance info... Perhaps a link to receive with some better design????
=> fixes bug causing application to crash when balances unavailable

app/containers/LoginLocalStorage/LoginLocalStorage.jsx, app/containers/Settings/Settings.jsx, app/modules/generateWallet.js
There is currently a gap in the handling of addresses without keys in the NEP6 wallet JSON. The proposal mentions that, `This field can be null (for watch-only address or non-standard address).`, however there were not any checks for this use case on file import or read.
Added checks on wallet file import to filter out accounts with no key, since this is not a part of the user flow for neon-wallet.
Also added checks on usages in the login from local storage and setting page. While the import filter should remove these records in the first place, this should not be needed. However the checks were still added just in case, as the result is an app crash if they do occur.
In order to test this, you can import a NEP6 …
=> Fix missing checks for null account key in NEP6 wallet file

app/containers/Home/Home.jsx, app/containers/Home/Home.scss
This solves https://github.com/CityOfZion/neon-wallet/issues/731 its also something that has been brought up multiple times in the past.
Version number is now extremely easy to see and reference
By pulling in version num from `package.json`
Updating version num in pack also updated it in the UI
NOTE: This design change has been confirmed with design team however mocks are not up to date
=> adds styled version num from package.json to Home.jsx

app/actions/settingsActions.js
`getTokenBalances()` will throw an error if any of the token hashes entered do not have a length of 40 chars... You can see the dozens of support requests coming in due to this simple mistake (there was no validation of script hashes in manage tokens and many many people just entered garbage here)
This PR addresses that issue by ignoring token hashes that do not have a length of 40
=> [v2] Feature/filters out invalid hashes

app/hocs/withThemeData.js
The theme data HOC breaks when local storage is cleared from Application Support... for now I am hard coding the theme and will come back to fixing this issue when we move forward with implementing Dark theme.
=> hard coded light theme

app/actions/settingsActions.js, app/hocs/withThemeData.js
Currently, when blasting away local storage from `Library/Application Support/Neon` (on a fresh install of v2) there are a few issues related to the way we load default settings data. This PR fixes that flow and also simplifies `settingsActions.js` it also resolves the hardcoded fix implemented here so that when we do get around to implementing themes it will be less painful https://github.com/CityOfZion/neon-wallet/pull/1474
=> settingsActions.js enhancements

app/containers/App/Sidebar/Sidebar.scss
N/A
Fixes the jumping that occurs when hovering the sidebar menu items.
Increases the transparent width border to 4x from 2x
Retested the flow and the items do not jump anymore.
No.
No.
=> fix(sidebar): Jumping menu items

app/containers/Home/Home.scss, app/containers/LoginLedgerNanoS/LoginLedgerNanoS.jsx, app/ledger/neonLedger.js
#1335 
Enhances the user experience with a more intuitive login flow with Ledger.
I consolidated the different errors/states into 3 stages - NOT_CONNECTED, OPEN_APP, CONNECTED and created a new UI which shows these stages. (approved by Ben)
Tested a lot with the Ledger. It works great, however there are occasions where the Ledger would go to a previous stage when selecting NEO app from Ledger (just for a sec), and then shows all steps are complete.
I have exported `neonLedger.js` error messages so I could handle them in the client side …
=> feat(login): Implement a more intuitive login flow with ledger

main.js
This PR hides the window from the screen until the application is ready preventing the buggy looking white screen you currently see for about 10 seconds 
when opening the app.
**FIXES:**
=> hides BrowserWindow until ready-to-show event

app/components/Send/SendPanel/SendRecipientList/SendRecipientList.scss, app/components/Send/SendPanel/SendRecipientList/SendRecipientListItem/index.jsx, app/util/nns.js
This implements a name to address resolutions using NEO Name Service.
When a user inputs a `.neo` domain name into the address field on the send screen, a quick attempt will be made to resolve it to an address. If successful, the field will be populated with the appropriate address. If the name is not found a error message will display on the input field.
=> Add NNS name lookup to send screen address input

app/core/constants.js
#1516 
Fixes ledger confirmation when sending assets.
The `BIP44_PATH` constant contained a default account `00000000` (probably from legacy code). The BIP44 function in the ledger code already adds the account... so this resulted in an invalid message being passed to the ledger.
Tested on one asset (GAS) with and without a priority free.
No.
Sending multiple assets seem not to work correctly, but this is not related to the issue.
=> fix(ledger): Fixes ledger confirmation when sending a tx

app/ledger/neonLedger.js
#1519 
Amends the text when denying on ledger
Amended the tx in `neonLedger.js` for the TX_DENIED message code.
No
No
=> fix(ledger): Fixes TX denied error message

app/actions/settingsActions.js, app/containers/Settings/Settings.jsx, app/containers/Settings/Settings.scss
fixes https://github.com/CityOfZion/neon-wallet/issues/1538
and a layout bug causing a vertical overflow at the default resolution...
=> fixes layout bug and adds version

app/containers/Settings/Settings.jsx
N/A
Removes the search option from network / block explorer selection in settings. I have consulted with @comountainclimber about this and we agreed that a search shouldn't be for network / block explorer as these have very few options.
Added `isSearchable={false}` to the React Select component.
Tested it manually
No
No
=> fix(settings): Removes search from network/block explorer selection

app/containers/Send/Send.jsx
N/A
The amounts panel was filtered when a send was initiated resulting in a very weird UI experience.
Removed filtering when sending/confirming the assets.
Tested manually
No
No
=> fix(amounts-panel): Removes asset filtering from amounts panel when sending

app/components/Blockchain/Transaction/Transaction.jsx
N/A
1. Disables mint tokens address from being added as a contact. (the address "MINT TOKENS" is invalid anyway).
2. The "Add" was inconsistent for an existing contact for the send/receive sections... Basically, the receive section would remove the "Add" button while the send would just disable it. I disabled it in both cases.
3. Code cleanups.
Manually tested it
No
No
Before:
After:
=> fix(transactions): disables mint tokens address from being added as a contact + cleanups

app/components/Blockchain/Transaction/Transaction.jsx
N/A
Network fee type was centered and had a larger font than the other types such as mint.. this created an inconsistency in the way the screen is rendered. (please see attached screenshot)
Removed the class that had these styling.
Manually tested it
No
I wasn't sure if this was the intended behavior... but in my view, this should be consistent.
Before: 
After:
=> fix(transaction): Network fees font/alignment

__tests__/core/explorer.test.js, app/core/explorer.js
N/A
1. Antchain tx link was broken on both MainNet / TestNet. (missing `0x` prefix)
2. Removed NEOVerse explorer because it was not used.
3. Wrote tests for getExplorerAddressLink
4. Cleanup the code and throw an error when passed with an unknown explorer.
Tested manually
No
No
Before:
http://antcha.in/tx/hash/56ec628ec9dc5383869e053fe685d23457d48dedc7fe63b75a40ef0a746ec6f8 (broken)
After:
http://antcha.in/tx/hash/0x56ec628ec9dc5383869e053fe685d23457d48dedc7fe63b75a40ef0a746ec6f8
=> fix(explorer): fixes broken antchain tx link + cleanups

app/actions/settingsActions.js, app/containers/Settings/Settings.jsx, app/core/constants.js
N/A
The settings dropdown did not show the correct block explorer label and always defaulted to neo scan.
Since the saved value is `this.props.explorer` (the value of `EXPLORERS`), the right label is actually `this.props.explorer`.
Tested it manually.
Exported a new `DEFAULT_EXPLORER` for consistency.
No.
=> fix(settings): display the correct label for selected block explorer

app/components/Inputs/NumberInput/NumberInput.jsx, app/components/Receive/QRCodeForm/QrCodeForm.jsx, app/components/Send/SendPanel/SendRecipientList/SendRecipientListItem/index.jsx, app/components/Send/SendPanel/index.jsx, app/containers/Send/Send.jsx, app/containers/TokenSale/TokenSale.jsx, app/core/formatters.js
N/A
Currently, the wallet crashes when you try to send a large amount > `999`. This PR solves this problem by only storing the raw value and not the formatted one produced by `Cleave.js`.
I have removed the `customChangeEvent` which was sort of a workaround around the fact that the `onChange` event did not return the `event` object. A better approach for the handler is to use `onChange => (event, value)`. By returning the raw value from the NumberInput it is now possible to remove all the instances of the comma removal.
I have also cleaned `handleFieldChange` method a bit.
Tested a lot manually!
**Are there …
=> fix(number-input): use raw value instead of formatted

app/modules/sale.js, app/modules/transactions.js
- Because `getNode`will return an empty object the most recent change to `transactions.js` and `sale.js` allowing for handling of node selection broke if you were running the application for the first time. This PR fixes that problem
NOTE: after manually choosing "Automatic" selection the node gets saved as an empty string in storage. This is the reason I was unable to detect the bug previously in my tests. isEmpty works the same for both empty strings and empty objects
=> fixes automatic node select bug in sale.js and transactions.js

__tests__/components/__snapshots__/NetworkSwitch.test.js.snap, app/components/Dashboard/PriceHistoryPanel/PriceHistoryPanel.jsx, app/components/Dashboard/PriceHistoryPanel/PriceHistoryPanel.scss, app/components/Inputs/StyledReactSelect/StyledReactSelect.jsx
Currently, the dashboard chart duration switcher is a click-to-change implementation.
This commit swaps it for a dropdown as requested in #1626.
Implemented using `<StyledReactSelect>` with some custom styling to match the design.
Passes all tests, no new tests added (lmk if this feature requires it).
=> [#1626] Implemented chart duration dropdown

app/components/AmountsPanel/AmountsInfoBox/AmountsInfoBox.scss, app/components/AmountsPanel/AmountsPanel.scss, app/components/Blockchain/Transaction/Transaction.scss, app/components/Contacts/EditContactPanel/EditContactPanel.scss, app/components/Dashboard/AssetBalancesPanel/AssetBalancesPanel.scss, app/components/Dashboard/PriceHistoryPanel/PriceHistoryChart.scss, app/components/Dashboard/PriceHistoryPanel/PriceHistoryPanel.scss, app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.scss, app/components/HeaderBar/HeaderBar.scss, app/components/Modals/ReceiveModal/style.scss, app/components/Modals/SendModal/SendModal.scss, app/components/NodeSelectPanel/NodeSelectPanel.scss, app/components/Panel/FullHeightPanel/FullHeightPanel.scss, app/components/Panel/Header.scss, app/components/PanelHeaderButton/PanelHeaderButton.scss, app/components/Receive/QRCodeForm/styles.scss, app/components/Send/PriorityFee/PriorityFee.scss, app/components/Send/SendPanel/SendPanel.scss, app/components/Settings/SettingsItem/SettingsItem.scss, app/components/Settings/SettingsLink/SettingsLink.scss, app/components/TokenSale/TokenSaleConfirm/TokenSaleConfirm.scss, app/containers/App/Sidebar/Logout/Logout.scss, app/containers/App/Sidebar/Sidebar.scss, app/containers/Dashboard/Dashboard.scss, app/containers/EditWallet/EditWallet.scss, app/containers/Home/Home.scss, app/containers/Settings/Settings.scss, app/containers/WalletManager/WalletManager.scss, app/styles/main.global.scss
Fixes #1639.
Make sure all Gotham font-family properties have generic font fallback (i.e. San-Serif).
For simplicity and and minimal files size gains, I implemented css vars.
```css
:root {
--font-fallback: 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
--font-gotham: 'Gotham', var(--font-fallback);
--font-gotham-medium: 'Gotham-Medium', var(--font-fallback);
--font-gotham-bold: 'Gotham-Bold', var(--font-fallback);
--font-gotham-thin: 'Gotham-Thin', var(--font-fallback);
--font-gotham-book: 'Gotham-Book', var(--font-fallback);
}
```
Then replaced it in all relevant scss files.
Create a style lint rule that enforces this.
=> [#1639] Added font-family fallbacks to all non-generic declerations

app/containers/Notifications/overrideStyles.js
Fixes #1675.
Notification text doesn't have any right padding to prevent overlap with close button. Ez fix.
Before:
After:
=> [#1675] Fixed notification text overlapping

app/modules/generateWallet.js
Fixes #1640 
Showing error message if account label in imported wallet already exists in a current account.
Intersecting account labels in current wallet and imported wallet as an indication of dupe name.
=> [#1640] Added wallet import name duplication validation

app/containers/Send/Send.jsx
**What current issue(s) from Trello/Github does this address?** 
#1700 
The regression issue with Neon being unable to send tokens with 0 decimals again. This is caused by a comparison relying on the following assignment in Send.jsx:
```const decpoint = amountNum.toString().length - 1 - amountNum.toString().indexOf('.')```
When no decimals are provided, `indexOf('.')` returns a value of `-1`, which causes the expression to evaluate to `1` instead of `0`, so the comparison of ```decpoint > toNumber(get(foundToken, 'decimals', 8))``` below it results in an error for zero-decimal tokens, since `1 > 0`.
Added logic to ensure zero decimals in the input translates to zero decimals in the comparison check in …
=> fix for zero decimal token size calculation bug

app/modules/generateWallet.js
@drptbl [suggested](https://github.com/CityOfZion/neon-wallet/issues/1640#issuecomment-440433218) to indicate duplicate wallet names in import error message.
Before, regardless of how many duplicates were found, the error message stated:
`A wallet with this name already exists locally`.
Now specifying wallet name:
And for multiple duplicates:
=> [#1640] Added detail to duplicate wallet name error message

app/components/Dashboard/PriceHistoryPanel/index.js
Fixes #1715 
The duration change action works with `duration` and `currency`
```
const mapPriceHistoryActionsToProps = (actions, props) => ({
setDuration: (duration: Duration) => {
props.setDuration(duration)
return actions.call({ duration, currency: props.currency })
}
})
```
But I noticed `withCurrencyData` doesn't update `props` until _after_ the actions are mapped - hence I assume it falls back to default currency which is the bug reported.
Bumped it up and it's works now🤘
=> [#1715] Fixed wrong chart currency when changing duration

app/components/Modals/BaseModal/BaseModal.scss, app/components/Modals/ReceiveModal/ReceiveModal.jsx, app/components/Modals/ReceiveModal/style.scss, app/components/Modals/SendModal/ConfirmDetails/ConfirmDetails.jsx, app/components/Modals/SendModal/ConfirmDetails/ConfirmDetails.scss
https://github.com/CityOfZion/neon-wallet/issues/1580
This PR labels the details of a nep9 payment request for UI clarity... It also updates the labels in Receive for consistent verbage and style
Manually reviewing the UI.
This PR also updates the style of the back button in modals as it was using the wrong color previously.
=> feature: adds labels to payment request details

__tests__/modules/metadata.test.js, app/modules/metadata.js, package.json, yarn.lock
Fixes #1718 
It's reported that although app is up-to-date, an error message suggesting upgrade appears frequently on app start.
1. Stalling version check till network connection is on.
2. Applied retry mechanism upon API request fail.
3. Suppressed error message (till implementing remote logging 😉)
1. Mocked app version and got upgrade notification.
2. Turned off internet connection, started app, logged in, turned internet connection back on and verified the API request went out thereafter.
3. Changed API url to http://httpstat.us/500 and verified 4 consecutive network requests.
=> [#1718] Version check revision

app/components/Contacts/EditContactPanel/EditContactPanel.jsx, app/components/Contacts/EditContactPanel/index.js
fixes https://github.com/CityOfZion/neon-wallet/issues/1702
makes confirmation modals consistent throughout the application
by leveraging our confirm modal type
I verified the happy and unhappy paths... when an error is thrown from `contactsActions.js` the error notification will show and prevent the confirmation modal from showing.
N/A
N/A
=> feature: implements confirm modal for contact deletion

app/modules/generateWallet.js
@drptbl reported dup wallet importing shows error but persists the import. It's a bug I introduced in #1716. SHAME 😓
TIL `reject` doesn't terminate `Promise` execution.. Added the missing `return` after rejection.
=> [#1640] Fixed import wallet non-terminating execution bug

__tests__/actions/nodeStorageActions.test.js, app/actions/balancesActions.js, app/actions/nodeStorageActions.js, app/core/constants.js, app/core/networks.js, flow-typed/declarations.js
This PR begins the iterative process of issue/enhancement https://github.com/CityOfZion/neon-wallet/issues/1712 - Specifically it adds an expiration to the "best node" algo and also sets an expiration on manually set nodes... This will resolve a number of _possible_ latent issues around the current set up
Because nodes could potentially fall behind go offline etc leaving them in memory (or local storage) permanently is generally a bad idea
node url is set in storage with a timestamp which is always compared to the current time... if its expired the node selection algorithm is run
By manual and automated test …
=> feature: node cache/storage expiration

__tests__/util/poll.test.js, app/util/poll.js
Preparation work for solving #1318.
**tl;dr** Added unit tests to `util/poll.js` before screwing with it
1. (#1730) PrepWork 1/3: Added util/poll.js unit tests ☜☜☜ _**YOU ARE HERE**_
2. (#1731) PrepWork 2/3: Made util/poll.js cancellable with cancellablePoll
3. (#1731) PrepWork 3/3: Added cancellablePoll unit tests
4. (#1732) Actual 1/2: Enable “Scan QR” button only if camera available
5. (#1733) Actual 2/2: Added camera availability unit tests
This is prepare work for the actual feature - Enabling/disabling “Scan QR” button depending on camera availability.
Since the next commit will be adding functionality to `util/poll.js` (making it cancellable), it would be wise to first cover the existing functionality with a few tests, so we're confident nothing breaks.
**Tests:**
1. Should stop …
=> [#1318] PrepWork 1/3: Added util/poll.js unit tests

__tests__/util/poll.test.js, app/util/poll.js
Preparation work for solving #1318.
**tl;dr** Added cancellablePoll
NOTICE: This PR is dependent on #1730. Please defer review until merged.
1. (#1730) PrepWork 1/3: Added util/poll.js unit tests
2. (#1731) PrepWork 2/3: Made util/poll.js cancellable with cancellablePoll
3. (#1731) PrepWork 3/3: Added cancellablePoll unit tests ☜☜☜ _**YOU ARE HERE**_
4. (#1732) Actual 1/2: Enable “Scan QR” button only if camera available
5. (#1733) Actual 2/2: Added camera availability unit tests
This is prepare work for the actual feature - Enabling/disabling “Scan QR” button depending on camera availability.
The main feature (next commit) polls continuously for camera availability. It's important to cancel the polling if the user clicks away from the login tab.
**Tests:**
Previous poll tests keep …
=> [#1318] PrepWork 2+3/3: Added cancellable ability to util/poll.js

__tests__/components/__snapshots__/Login.test.js.snap, __tests__/util/poll.test.js, app/containers/LoginPrivateKey/LoginPrivateKey.jsx, app/containers/LoginPrivateKey/index.js, app/hocs/withCameraAvailability.js, app/util/poll.js, flow-typed/declarations.js
Fixes #1318.
**tl;dr** The actual feature work
NOTICE: This PR depends on #1730 and #1731 to be merged so defer review till then plz.
1. (#1730) PrepWork 1/3: Added util/poll.js unit tests
2. (#1731) PrepWork 2/3: Made util/poll.js cancellable with cancellablePoll
3. (#1731) PrepWork 3/3: Added cancellablePoll unit tests
4. (#1732) Actual 1/2: Enable “Scan QR” button only if camera available  ☜☜☜ _**YOU ARE HERE**_
5. (#1733) Actual 2/2: Added camera availability unit tests
The main feature finally. Basically, once the Private Key Login tab is clicked, the "Scan QR" button isn't enabled until a camera source is found (not "active" but rather "available" in the OS).
This enhancement to `LoginPrivateKey` is implemented with an HOC `withCameraAvailability` which adds a prop `cameraAvailable` …
=> [#1318] Actual 1/2: Enable “Scan QR” button only if camera available

__tests__/components/Login.test.js, __tests__/components/__snapshots__/Login.test.js.snap, __tests__/testHelpers.js, __tests__/util/poll.test.js, app/containers/LoginPrivateKey/LoginPrivateKey.jsx, app/containers/LoginPrivateKey/index.js, app/hocs/withCameraAvailability.js, app/util/poll.js, flow-typed/declarations.js
Part of the #1318 fix.
**tl;dr** The actual feature unit tests
NOTICE: This PR depends on #1730, #1731 and #1732 to be merged so defer review till then plz.
1. (#1730) PrepWork 1/3: Added util/poll.js unit tests
2. (#1731) PrepWork 2/3: Made util/poll.js cancellable with cancellablePoll
3. (#1731) PrepWork 3/3: Added cancellablePoll unit tests
4. (#1732) Actual 1/2: Enable “Scan QR” button only if camera available
5. (#1733) Actual 2/2: Added camera availability unit tests  ☜☜☜ _**YOU ARE HERE**_
Added a test that mocks camera availability, then polls for the expected dom change - "Scan QR" button enable/disable. Had to create an enzyme `waitForElement` utility since the polling is set to a 1s interval.
=> [#1318] Actual 2/2: Added camera availability unit tests

app/util/poll.js
@comountainclimber [said rightfully](https://github.com/CityOfZion/neon-wallet/pull/1731/files/57ddc3db408b090dfb14ce469c8c9c0e59b476fe#r237591080) that `retry` in `poll` is needlessly repeatedly being redefined, so this commit pulls it out. All tests pass and checked manually that camera availability feature still operating.
=> Quick Poll perf optimization

__tests__/setupTests.js
By disabling all http requests we were not actually running our full integration tests in `nodeStorageActions.js` this PR changes that by _not_ disabling all http requests for our test suite
Fixes error being thrown from happy path in `getRPCEndpoint()``
```
Error: NetConnectNotAllowedError: Nock: Not allow net connect for "test1.cityofzion.io:443/"
```
By allowing the host machine running the tests to ping the node
By running the test suite `yarn test` and seeing the error being thrown in the console removed.
**Is there anything else …
=> feature: updates setupTests.js

app/components/Modals/SendModal/ReadCode/ReadCode.jsx, app/components/Modals/SendModal/ReadCode/index.js, app/containers/LoginPrivateKey/LoginPrivateKey.jsx
Fixes #1743
1) Code duplication between `QRCodeScanner` and `LoginPrivateKey`
2) Missing disable/enable "capture" button feature in `Send` Modal
Two separate commits:
1) Luckily an independent `QRCodeScanner` component already exists, so adapting `LoginPrivateKey` was a cinch.
2) Added `withCameraAvailability` to `ReadCode`. Don't you just love HOC?
1) Manually tested that logging in by scanning private key QR code works.
2) Manually tested that upon disconnecting webcam, the "capture" button in `Send` modal gets disabled.
All code is special. [Although..](https://i.imgflip.com/1pfyt0.jpg)
**Is …
=> [#1743] 1/3: Merging code and features for similar QR Scan modules

app/core/nodes-main-net.json
https://github.com/CityOfZion/neon-wallet/issues/1707
After reviewing the results returned from `https://api.neoscan.io/api/main_net/v1/get_all_nodes` it is evident that numerous nodes in this list are no longer being maintained (or are offline for some other reason). This PR solves that problem by removing them from our hard coded list
Attempted to ping the RPC nodes, reviewed their status on http://monitor.cityofzion.io/
Manual testing
=> feature: removes deprecated RPC nodes

app/components/QrCodeScanner/QrCodeScanner.jsx, app/components/QrCodeScanner/index.js, app/containers/App/Loading.js, app/containers/App/Loading.scss, app/containers/Home/Home.scss
Fixes #1576 
DEPENDS ON #1744. Plz do not merge before #1744 or the commit history could get messy.
It was reported that the webcam preview might take up to 5 secs to initialize and a loading indicator is needed.
Added a loading indicator to `QRCodeScanner` which affects both Private Key Login and Send modules thanks to #1744 😋.
Manually tested that:
a) Other loading indicators remain unaffected.
b) Loading indicator shows up and runs smoothly in both cases.
Plz notice that commits from #1744 are included so only review commit cd1b19e
I've added specific comments in the GitHub commit code.
**Is …
=> [#1576] 2/3: QR Scan loading indicator

app/components/Modals/SendModal/ReadCode/ReadCode.jsx, app/components/Modals/SendModal/SendModal.jsx, app/components/QrCodeScanner/QrCodeScanner.jsx, app/components/QrCodeScanner/QrCodeScanner.scss, app/components/QrCodeScanner/index.js, app/containers/App/Loading.js, app/containers/App/Loading.scss, app/containers/Home/Home.scss, app/containers/LoginPrivateKey/LoginPrivateKey.jsx, app/util/ConditionalLink.jsx
Fixes #1582 
DEPENDS ON #1745. Plz do not merge before #1745 or the commit history could get messy.
Firing up the webcam for QR scanning could fail for the following reasons:
a) Camera already in use by other program (I read it [here](https://stackoverflow.com/questions/43919639/what-is-a-trackstarterror))
b) App denied access to camera (easily reproducible)
c) Some unknown reason
Our UI doesn't reflect that to the user:
I now catch all errors and show a "Could not connect to camera" error where the webcam preview is expected.
Specifically for `TrackStartError` which adheres to reasons (a) and (b) I add a short note for the user to check that no other program is using the camera and refer to grant appropriate …
=> [#1582] 3/3: Added QR scan error handling

app/modules/generateWallet.js
Addresses #1688 
Importing PK+passphrase that already exist locally yields an error notification along with a "wallet imported" success message.
My solution is actually superficial - takes care of this specific case before continuing to server.
But I don't think it solves the REAL issue.
AFAIK the real issue is that as a `NEW_WALLET_ACCOUNT` is dispatched
https://github.com/CityOfZion/neon-wallet/blob/545bf77ca68f2da0b4c02483727ba2e794fedfff/app/modules/generateWallet.js#L240-L251
an unconditional redirect occurs to `DisplayWalletAccounts`
https://github.com/CityOfZion/neon-wallet/blob/545bf77ca68f2da0b4c02483727ba2e794fedfff/app/modules/generateWallet.js …
=> [#1688] Added client side import validation for account key

app/containers/Notifications/overrideStyles.js, app/modules/metadata.js, app/modules/notifications.js, app/styles/main.global.scss, main.js
https://github.com/CityOfZion/neon-wallet/issues/743
- The link in the version check notification will now behave like the other links found throughout the application
- Fixes a few issues related to styles (low contrast problems)
BEFORE:
AFTER:
By using electron's `shell.openExternal` https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options-callback
Manual testing...
`NotificationArgsType` has been updated to include children - see the React Notificaiton System documentation …
=> feature: updates version check notification

app/actions/transactionHistoryActions.js
https://github.com/CityOfZion/neon-wallet/issues/1682
Currently is a user adds a script hash the symbol type will not show in the activity page. This PR fixes that problem.
This PR uses neon-js's `getToken` to fill missing symbol data in the activity page for the edge case user's token is not included in `tokenList.json`
By manually testing
If request for token info fails for whatever reason the code will default to the current behavior in 2.0.0
=> feature: adds custom tokens to activity page

__tests__/components/__snapshots__/Login.test.js.snap, app/components/Inputs/TextInput/TextInput.js, app/containers/Home/Home.scss, app/containers/LoginPrivateKey/LoginPrivateKey.jsx
This PR fixes https://github.com/CityOfZion/neon-wallet/issues/1737
Users are unable to see the full string of the WIF when pasted into the home screen private key login input.
I solve this by fixing broken concatanation of classNames in TextInput.js and passing down a CSS class that keeps the placeholder at 14px but reduces the font to 12px. 
Tested with numerous private key combinations
=> feature: fix font size in private key input

.circleci/config.yml, package.json
After doing some review of our circleCI set up, and a few hours of messing around I noticed a few issues...
- The path to our yarn cache was incorrect.
- Without the use of `--frozen-lockfile` flag in our yarn install command we were somehow generating a new lock file (within circleCI) that never matched the one we were committing - this was causing our "restore cache" step to always think that there was no cache based on the checksum.
- Without changing the name of the "save cache" key, circleCI was unable to properly update the existing cache (because yarn.lock was not being updates)
This update will dramatically reduce build times (50%+ reduction) as build, test, and deploy phases no longer have to run `yarn` when checksums match 🎉
=> feature: fixes config.yml to properly use caching

app/components/Modals/SendModal/ReadCode/ReadCode.jsx, app/components/Modals/SendModal/ReadCode/ReadCode.scss
Noticed that in the sketch design file there should be markers in the send modal QR scan rubric AND that there are related DOM elements in the code, but the markers do not appear.
Before | After
------------ | -------------
1) The existing DOM element classnames were in plain text instead of CSS module properties.
2) The design implementation wasn't totally accurate - the marker edges should be pointy.
1) Fixed classnames.
2) Implemented pointy edged with the css border transparent trick.
Manually gazed at it like a madman.
Since Sass …
=> Fixed missing frame lines in ReadCode

app/components/Modals/SendModal/ReadCode/ReadCode.jsx, app/components/Modals/SendModal/SendModal.jsx, app/components/Modals/SendModal/index.js, app/components/QrCodeScanner/QrCodeScanner.jsx, app/containers/LoginPrivateKey/LoginPrivateKey.jsx, app/containers/LoginPrivateKey/index.js
This is the last part of the QR Scan fix and refactor commits.
Since introducing scan pause state in #1760, the scanner has no way of knowing if and when to resume, so a constant 4 second wait is invoked after pause. That's suboptimal since callback response duration cannot be predetermined.
A safer method is to regard a callback error as an indication that scanning should be resumed. 
So I added `withProgress()` to the relevant components (thence #1761) and the scanner now acts upon progress changed from `LOADING` to `FAILED`.
Note: Listening to callback success events is irrelevant since the scanner component is abandoned thereafter.
**How did you make …
=> QR Scan - Resume on progress event instead of preset time

app/actions/pendingTransactionActions.js, app/components/Send/SendPanel/ActivityLink/ActivityLink.jsx, app/components/Send/SendPanel/ActivityLink/index.js, app/components/Send/SendPanel/SendError/index.jsx, app/components/Send/SendPanel/SendSuccess/SendSuccess.scss, app/components/Send/SendPanel/SendSuccess/index.jsx, app/containers/App/Sidebar/Sidebar.jsx, app/containers/App/Sidebar/Sidebar.scss, app/containers/App/Sidebar/index.js, app/modules/transactions.js, app/styles/main.global.scss, flow-typed/declarations.js
This PR is part II of https://github.com/CityOfZion/neon-wallet/pull/1766 and provides some subtle updates to the UI to help users understand the exact state of their unconfirmed transactions.
Further improves our send UX
By extending the work started in https://github.com/CityOfZion/neon-wallet/pull/1766
Manual testing locally
I updated `addPendingTransaction` to always return the retrieved information from the blockchain when adding a tx to storage so that the SideBar can know about only transactions returned from …
=> feature: UI enhancements for unconfirmed transactions flow

app/actions/dashboardActions.js, app/actions/pendingTransactionActions.js, app/util/findAndReturnTokenInfo.js
This issue was brought up in the CoZ slack channel
- Better representation of pending activity
- "Notification" of pending tx will get removed from sidebar after 2 confirmations OR the neoscan API returns  the transaction from the abstract endpoint
Because we were parsing the vout array to form the pending transactions getting added to the activity page occasionally this was not always creating the most desirable format see this transaction for instance https://neoscan.io/transaction/716e6606f17b3e2453bf9dd9037c1fdafe8bf527afb4cf37c9a29d45e14c9562 => now we simply reference the sendEntries array which resolves the issue
**How did you make sure your …
=> chore: fixes issues related to pending transactions UX

__tests__/components/__snapshots__/TransactionHistoryPanel.test.js.snap, app/components/TransactionHistory/TransactionHistoryPanel/TransactionHistoryPanel.jsx, app/components/TransactionHistory/TransactionHistoryPanel/index.js
N/A
This PR fixes a problem that was causing this for loop to unnecessarily be iterated over and thus calling `pruneConfirmedOrStaleTransaction()`
```
for (const transaction of toBePurged) {
// eslint-disable-next-line
await pruneConfirmedOrStaleTransaction(address, transaction.txid)
handleGetPendingTransactionInfo()
}
```
It also maps the `getPendingTransactionInfo` to props of the transaction history component so that the action can be dispatched after pending transactions are pruned from storage. This was causing issues in the delay between when the count in the sidebar would be removed. Previously the count would only decrement after two confirmations because the action was not being …
=> chore: fixes minor bugs in release

__tests__/components/__snapshots__/TransactionHistoryPanel.test.js.snap, app/components/Send/SendPanel/SendSuccess/index.jsx, app/components/TransactionHistory/TransactionHistoryPanel/TransactionHistoryPanel.jsx, app/components/TransactionHistory/TransactionHistoryPanel/index.js, app/containers/Dashboard/Dashboard.jsx, app/modules/transactions.js
This small PR adds polling to the `TransactionHistoryPanel` component (very similar how it is done in Dashboard) - enhancing user experience by allowing the activity tab to "refresh" itself every 30 seconds without forcing user to mash refresh. The polling will query the current selected node using getrawtransaction AND will query the neoscan API
This PR also changes some verbage in the app from "completed / complete" to "pending"
Careful manual testing.
=> feature: adds polling to activity tab

app/core/tokenList.json
Bridge Protocol has updated the NEP5 token from TOLL to BRDG. The TOLL token will not be used anymore. Also BRDG has a lower supply than TOLL because of a token burn event.
https://neonewstoday.com/general/bridge-protocol-to-conduct-token-swap-from-toll-to-brdg/
=> Updated TOLL to BRDG token with new supply

app/core/nep5.js
Before the release of v2 it was suggested that we eliminate the need to rely on github for token hash data since then it was proposed that this feature be brought back.
This PR eliminates the need to release a new binary when we want to add token hash data to the application.
By fetching the data from `https://raw.githubusercontent.com/CityOfZion/neo-tokens/master/tokenList.json`
Testing locally
=> feature: reimplements dynamic token hashes

app/containers/TransactionHistory/TransactionHistory.jsx
This PR accomplishes two things:
1.) adds disabled state to the new export button in the activity tab so that users cant mash this (or automate the mashing)
2.) Updates the default path of the exported csv to `<path to documents>/neon-wallet-activity-${moment().unix()}.csv`
Verified manually that file export is still working exactly as expected
=> feature: activity export enhancements

README.md, package.json
When executing 'yarn dev' no indication of progress was showing before. Now the build status is output as it goes.
This PR also addresses an issue with Linux (experienced personally on Ubuntu 18.04) where 'yarn dev' builds but Neon never opens. A note was made on the readme.
The PR resolves the issue of no clear feedback to the developer of build progress.
This PR also addresses an issue with Linux (experienced personally on Ubuntu 18.04) where 'yarn dev' builds but Neon never opens. A note was made on the readme.
I added the flag --progress to the package.json build script named 'dev'.
I tested it and …
=> chore: yarn dev issues on Linux

app/containers/TransactionHistory/TransactionHistory.jsx, app/containers/TransactionHistory/TransactionHistory.scss, app/core/nep5.js, package.json
**release 2.2.1**
- The CSS styling of the export button was not correct in the light theme
- We were not properly copying over decimal amounts into the tokens list causing issues with certain nep5 transfers
- The export functionality was broken in certain edge cases (wallets with only 1 page worth of abstracts via the neoscan API)
=> hotfix: fixes issues with RC 2.2.0

app/containers/News/News.jsx
This PR simply reduces the size of the requested image assets for efficiency. Unfortunately parsing the XML has become somewhat weird/hard to read but I suppose that is just the nature of this beast (parsing a big string of html).
=> feature: reduces the size of the requested image assets in news feed

app/actions/authActions.js, app/containers/EditWallet/EditWallet.scss, app/containers/Home/Home.jsx, app/containers/Home/Home.scss, app/containers/LoginWatchOnly/LoginWatchOnly.jsx, app/containers/LoginWatchOnly/index.js, app/styles/main.global.scss
https://github.com/CityOfZion/neon-wallet/issues/1827
(begins the process of tackling https://github.com/CityOfZion/neon-wallet/issues/1846)
This PR serves as a feature in itself however it is really the foundation of adding additional features such as building transactions for offline signing...
NOTE: more work needs to be done here (coming in separate PRs) to ensure high quality user experience in watch only mode (We should disable the appropriate routes and possibly address some other items I am not thinking of now)
This gives the ability for users to enter in any valid address on the blockchain to use neon
By mostly reusing components and logic that …
=> feature: adds watch only address (part I)

app/containers/App/Sidebar/Sidebar.jsx, app/containers/App/Sidebar/index.js
This is part II of https://github.com/CityOfZion/neon-wallet/pull/1845
Improving the UX by conditionally rendering certain side nav items based on authentication method.
=> feature: adds watch only address (part II)

app/containers/Home/Home.jsx, app/containers/Home/Home.scss, app/containers/LoginWatchOnly/LoginWatchOnly.jsx, app/styles/main.global.scss
This simple PR accomplishes four things:
1.) Reduces clutter in the "login tabs" by removing excessive verbage
2.) Increases the font size of the text in the tabs
3.) Changes the placeholder text of the "Watch" option
4.) Reduces recent aspect changes to the width of the "Home" container
BEFORE:
AFTER:
=> feature: login verbage refactor

__tests__/components/__snapshots__/Login.test.js.snap, app/containers/Home/Home.scss, app/containers/LoginNep2/LoginNep2.jsx, app/containers/LoginNep2/index.js, app/containers/LoginPrivateKey/LoginPrivateKey.jsx, app/containers/LoginWatchOnly/LoginWatchOnly.jsx
https://github.com/CityOfZion/neon-wallet/issues/1854
This PR allows users to scan a QR of their encrypted key in order to login
NOTE: password still must be added
By reusing the components we already have in our lib and by using a similar flow as exposed in `LoginPrivateKey.jsx`
Manual testing
Currently the app does not expose any qr codes for encrypted keys however a future PR will add them in the appropriate places (both during wallet creation and in settings).  We should avoid merging this …
=> feature: adds encrypted key qr scan to login flow

app/components/Modals/ImportTransactionModal/ImportTransactionModal.jsx, app/components/Modals/ImportTransactionModal/index.js, app/hocs/withAuthData.js, app/modules/transactions.js
This builds off the work done in the `feature/sign-transactions` branch in order to add support for offline signing
Gives the ability for our users to use a ledger nano to sign transactions offline
By digging around the code base, using utility functions from neon-js
Manual testing of multiple different transactions and transaction types
=> feature: ledger support for offline signing flow

__tests__/store/reducers.test.js, app/components/Root/Routes.jsx, app/components/Settings/EncryptPanel/EncryptPanel.jsx, app/components/Settings/EncryptPanel/index.js, app/components/Settings/EncryptQR/EncryptQR.jsx, app/components/Settings/EncryptQR/EncryptQR.scss, app/components/Settings/EncryptQR/index.js, app/components/Settings/EncryptSuccess/EncryptSuccess.jsx, app/components/Settings/EncryptSuccess/EncryptSuccess.scss, app/containers/DisplayWalletAccounts/DisplayWalletAccounts.jsx, app/containers/DisplayWalletAccounts/DisplayWalletAccounts.scss, app/containers/DisplayWalletAccounts/DisplayWalletAccountsQrCodes/DisplayWalletAccountsQrCodes.jsx, app/containers/Encrypt/Encrypt.jsx, app/containers/Encrypt/index.js, app/core/constants.js, app/modules/generateEncryptedWIF.js, app/modules/index.js
#1862
The PR add the feature to render QR code for the encrypted key.
I followed more or less the logic for rendering the QR code for private key and public address and adapted it for the encrypted key. This logic is essentially stored in these two modules: 
- `DisplayWalletAccountsQrCodes`
- `DisplayWalletAccounts`
- I tested manually the rendering of the encrypted key QR for these two scenarios:
1) `Create Wallet`
2) `Encrypt Key` (option available in the setting section.)
- I also did run `yarn test` and all the existing tests are passing.
**Are there any special changes in the code that we should be …
=> feature suggestion: We should render a QR for encrypted keys (without passwords)

app/containers/DisplayWalletAccounts/DisplayWalletAccounts.scss
Fixes a minor CSS bug in the `DisplayWalletAccounts.jsx` component. Related PR can be found here https://github.com/CityOfZion/neon-wallet/pull/1873
BEFORE:
AFTER:
=> chore: fixes margin bug in DisplayWalletAccounts.scss

package.json, yarn.lock
Because yarn does not have the equivalent of `npm audit fix` this is the next best thing and should address all the items below:
=> chore: Addresses npm security vulnerabilities

app/components/Send/SendPanel/index.jsx
N/A
To avoid confusion with our users we only present the button to generate a transaction for offline signing when the user is logged in via watch only mode
With a simple ternary in the JSX that was basically already there
Manual testing
=> feature: only render 'generate transaction JSON' button in watch only mode

__tests__/core/wallet.test.js, app/core/wallet.js
#1899
When sending a transaction from an account with balance more than 15 significant digits, neon-wallet is unable to process the transaction because the balance can't be used as input to create a `bignumber` object. This is a limitation of the package bignumber.js version 5.0.0.
**How did you solve this problem?** 
We did a workaround and used an alredy existing method, `toBigNumber`, to generate a bignumber object from an input whose type is a number and with more 15 significant digits.
Tested manually :
https://neoscan-testnet.io/transaction/e0d08eda33891e16700819a62ae83a04aa73a5bdd4daa24fa05ad2b1ee26f7b4
**Are there any special changes …
=> Fix sending transaction from an account with balance more than 15 significant digits.

app/actions/pricesActions.js, app/core/nep5.js, app/core/tokenList.json, flow-typed/declarations.js
#1889 
Often the token symbol in `tokenList.json` does not match the [cryptocompare](https://www.cryptocompare.com/) api symbol. For these exceptions, the api does not deliver any price for the token. With this PR we make the exception handling of such cases configurable (as suggested by @hal0x2328 ). For instance to fix the token `simbol AVA` going forward, we simply add the corresponding `cryptocompareSymbol  AVALA` in the `tokenList.json`.
Adjusted the code to consume the new cryptocompareSymbol key in the `tokenList.json`.
manual testing:
**Are there any special changes in the code that we should be …
=> Add configurable price exception handling of token symbol

app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.jsx, app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.scss, package.json, yarn.lock
This PR updates the 'Token Balances' panel on the dashboard so that the name column (`token.name` from the neo-tokens repo) is removed and we simply refer to symbol. It also updates the column header from 'Ticker' to 'Token'. Thank you @dauTT for the recommendation
=> feature: simplify token balances panel

__tests__/actions/blockHeightActions.test.js, __tests__/components/Sidebar.test.js, __tests__/components/__snapshots__/Sidebar.test.js.snap, app/actions/accountActions.js, app/actions/blockHeightActions.js, app/containers/App/Sidebar/Sidebar.jsx, app/containers/App/Sidebar/Sidebar.scss, app/containers/App/Sidebar/index.js, app/containers/Buttons/RefreshButton/index.js
https://github.com/CityOfZion/neon-wallet/issues/1833
This PR adds the current block height of the selected node to the sidebar component. It will update anytime the refresh button is click OR it will update automatically as per the refresh polling
Manual and unit testing
- In the future it would be a nice enhancement to add some sort of CSS transition into the number incrementing
- Might be nice to add a tooltip displaying the network, currently selected RPC node etc
=> feature: adds block height data to Sidebar component

app/core/tokenList.json
Updates the fallback token list in the event that github is down. The "actual" PR to update this in production can be found here:
https://github.com/CityOfZion/neo-tokens/pull/63
=> feature: Updates LX hash in tokenList.json

package.json, yarn.lock
This PR takes care of a few npm security alerts issued by github over the past few weeks
=> chore: Pins versions for npm audit in package.json

.circleci/config.yml
This PR fixes the breaking build step that just started occurring in circleCI seems to be directly related to the update here: 
https://github.com/electron-userland/electron-builder/commit/d33065bd7b7c5b21182d7a6ef03c45d5bbab5c50
=> critical feature: fixes broken windows build step in circleCI

README.md, __tests__/components/__snapshots__/Settings.test.js.snap, app/assets/flags/russia.svg, app/components/Root/IntlWrapper.jsx, app/core/constants.js, app/translations/index.js, app/translations/russian.js
Russian localization
I provided translated strings and a flag
I tested in local env
No all parts of the app are hooked with the localization.
No but existing test snapshots are updated
=> Russian localization

__tests__/components/__snapshots__/Settings.test.js.snap, app/core/constants.js
There's no issue, I just found the bug while using the software.
This fix the translation of the word french into french (Francés is wrong, should be Français).
By changing the translation to the right one.
It's just a string.
No.
No.
No.
=> Fix french language translation

app/containers/Settings/Settings.jsx
None, I didn't create an issue
#1998 updated the electron version from ancient (`2.x`) to recent (`8.5.2`). With the new electron version the [showSaveDialog()](https://github.com/electron/electron/blob/v8.5.2/docs/api/dialog.md#dialogshowsavedialogbrowserwindow-options) no longer accepts a callback as argument, but returns a promise. As a result wallet exporting currently does nothing (meaning; the dialog shows, but the JSON file is never written to disk). 
-edit-
same story for `showOpenDialog`. One place immediately related place I found was in importing the wallet I just exported. Didn't work. Now it does
Update code to be based on promises
**How did …
=> fix wallet export/import

.circleci/config.yml, app/containers/Home/HomeLayout.jsx, package.json
Used this fork to verify auto update working on MacOS, Windows and Linux
=> feature: CI enhancements

.circleci/config.yml, .gitignore, main.js, package.json, yarn.lock
This PR adds `electron-builder-notarize` to add a notarization step with Apple into the build process. It also sets up OTA updates and automates the release publishing step for windows and linux.
Simply push a tag up to github and electron-builder will create a draft release configured for auto updates using circleCI. MacOS artifacts must be manually generated via `yarn dist` on a machine with access to the CoZ apple developer cert and then added to the draft release
TODO:
=> feature: Sets up auto update for Linux/Windows/MacOS and and code signing/notarization on MacOS [WIP]

.circleci/config.yml
- Removes commented out e2e tets
- Removes duplicate "linux deploy" step (this [currently happens automatically using publish](https://www.electron.build/configuration/publish) on tag commits) during the build step
- Removes the storage of build artifacts as this is now unnecessary due to the built in publish step within `electron-builder`
=> feature: Updates config.yml

app/actions/balancesActions.js, app/core/tokenList.json
Because the RPC nodes return `SWTH` for both of the following contract hashes  (`ab38352559b8b203bde5fddfa0b07d8b2525e132` and `3e09e602eeeb401a2fec8e8ea137d59aae54a139`)  it was breaking balance logic within neon... 
This PR makes it so that the hashes map back onto the symbols for the token list found here => https://github.com/CityOfZion/neo-tokens/blob/master/tokenList.json such that those symbols are reflected in the UI and the broken logic is fixed
I also went ahead an updated the hard coded list that neon uses (in the event that github is down)
TODO: before this release goes out, update the neo tokens repo
=> feature: Fix potential duplicate symbol bug

app/actions/balancesActions.js, app/core/nep5.js, app/core/tokenList.json
=> feature: handles integer return type for SWTH contract + reduces network requests for balance info

__tests__/components/__snapshots__/Settings.test.js.snap, app/assets/flags/dutch.svg, app/components/Root/IntlWrapper.jsx, app/core/constants.js, app/translations/dutch.js, app/translations/index.js
None
The lack of the Dutch language
By translating and adding a Dutch flag to the ecosystem
By checking everything in line.
No
I had to recreate the Snapshots of the unittester by using `yarn jest --updateSnapshot` otherwise it wouldn't compile. Oh and Dutchies are cool.
=> New language: Introducing Dutch for Neon

app/actions/pricesActions.js
This PR makes it so that our internal API gets queried in the event that cryptocompare is down or client is rate limited....
Essentially just updates `getPrices()`to accept a conditional in which it will make the request to the alternate url in the event of the prices object being empty.
=> feature: adds backup pricing API

__tests__/components/__snapshots__/Settings.test.js.snap, app/actions/balancesActions.js, app/actions/contactsActions.js, app/actions/n3AccountsActions.js, app/actions/pendingTransactionActions.js, app/actions/transactionHistoryActions.js, app/components/Blockchain/Address/Address.jsx, app/components/Blockchain/Transaction/Transaction.jsx, app/components/Blockchain/Transaction/index.js, app/components/Contacts/AddContactPanel/AddContactPanel.jsx, app/components/Contacts/AddContactPanel/index.js, app/components/Contacts/ContactsPanel/ContactsPanel.jsx, app/components/Contacts/ContactsPanel/index.js, app/components/Contacts/EditContactPanel/EditContactPanel.jsx, app/components/Contacts/EditContactPanel/index.js, app/components/Dashboard/TokenBalancesPanel/index.js, app/components/Modals/ShowQrForExportModal/ShowQrForExportModal.scss, app/components/Send/SendPanel/index.jsx, app/containers/Contacts/index.js, app/containers/LoginLocalStorage/LoginLocalStorage.jsx, app/containers/Receive/Receive.jsx, app/containers/Send/Send.jsx, app/core/explorer.js, app/hocs/helpers/didLogout.js, app/modules/transactions.js, app/util/findAndReturnTokenInfo.js, config/webpack.config.prod.js, flow-typed/declarations.js, package.json, yarn.lock
=> correction in contacts screen to know when it is neo 3 or neoLegacy
