app/actions/index.js, app/actions/types.js, app/components/Login.js, app/components/NetworkSwitch.js, app/components/WalletInfo.js, app/reducers/index.js, app/wallet/api.js
new branch with a few fixes for pull request by @db383
=> Bittrex api

app/actions/index.js, app/actions/types.js, app/components/Login.js, app/components/NetworkSwitch.js, app/components/TransactionHistory.js, app/components/WalletInfo.js, app/reducers/index.js, app/styles/main.scss, app/wallet/api.js, app/wallet/index.js, package.json, webpack.config.js
add full transaction history + bugfixes
=> Transaction history

.gitignore, app/components/Login.js, app/wallet/index.js
Adde possibility to login with Hex private key.
I also added env/ to the gitignore as sass need python and I have virtualenvs locally.
=> Add Hex login

app/wallet/api.js, package.json
This:
- Change to COZ proxy (useful for asia / China)
- Change builder to NSIS (squirrel has problems in some locale)
- Fix the email string, to be able to build deb on Linux
=> Windows and Linux build fixes

app/components/CreateWallet.js, app/components/Login.js, app/components/NetworkSwitch.js, app/components/Send.js, app/components/TransactionHistory.js, app/components/WalletInfo.js, app/containers/Dashboard.js, app/styles/main.scss, app/wallet/index.js
=> Alpha release

__mocks__/fileMock.js, __tests__/components/Login.test.js, __tests__/components/__snapshots__/Login.test.js.snap, __tests__/reducers/index.test.js, app/components/Login.js, app/reducers/account.js, app/reducers/claimState.js, app/reducers/dashboard.js, app/reducers/generateWallet.js, app/reducers/index.js, app/reducers/metadata.js, app/reducers/transactionState.js, app/reducers/wallet.js, package.json
Unit Testing
- Tests that the Login component/container is calling the LOGIN action as proof that infrastructure works.
- Test the combination of the reducer
- Jest and Enzyme testing frameworks used.
- Made some changes to the Login component to make it more testable by replacing ref node input with accepting the event target's value directly.
- Refactored reducers into its own file with `index.js` being the combiner.
Manual logging in to TestNet and playing around.
Executing tests with command `jest`, `npm install -g jest` may be …
=> Unit test infrastructure

app/components/NetworkSwitch.js, app/wallet/api.js
=> Cmc balance

app/wallet/api.js
#32 
Fixing Github issue
By updating the bittrex getticker URL to use coinmarketcap
Manual test
Nope
Nope
=> Updated getMarketPriceUSD function to use USDT-NEO Bittrex API call

README.md
None that I know of
Hopefully will reduce the number of support questions that are created in github issues.
Add links for proper support channels, and add example questions that should not be put in github issues in the Readme file
Only time will tell
No
No
Not applicable
=> Update with documentation on support resources

app/components/CreateWallet.js, app/components/EncryptKey.js, app/components/LoginNep2.js, app/components/NetworkSwitch.js, app/components/TransactionHistory.js, package.json
=> Nep2 minor fixes before release

app/components/DisplayWalletKeys.js
=> some optimizations for wallet generation page

ISSUE_TEMPLATE.md
None.
Users requesting general software support on the developer GitHub
Creating an issue template to prompt users seeking support to go to Slack
Not possible
No
This is just a suggestion, feel free to disregard and create something else that suits
=> Initial suggested issue template

__tests__/components/TransactionHistory.test.js, __tests__/components/__snapshots__/TransactionHistory.test.js.snap
Testing the Neon Wallet
Tests the Transaction History Component
By writing a test to make sure the component is working correctly.
I ran the tests and got them to pass
I did not write a test to make sure the click through to the external neotracker.io site is working
This is my first open source commit :)
This is just a unit test :)
=> add tests for Transaction History Component

__mocks__/electron.js, __tests__/components/LoginNep2.test.js, __tests__/components/TransactionHistory.test.js, __tests__/components/__snapshots__/LoginNep2.test.js.snap, app/components/LoginNep2.js, package.json
Testing the Neon Wallet
Testing the LoginNep2 component
testing the functionality and snapshot of the component
running 'npm test'
In addition to the tests, I took out 'wif' and 'loggedIn' from mapStateToProps in the actual component since neither was being used. 
=> add tests for LoginNep2 component

__mocks__/neon-js.js, __tests__/components/LoginNep2.test.js, __tests__/components/NetworkSwitch.test.js, __tests__/components/WalletInfo.test.js, app/components/LoginNep2.js, app/components/NetworkSwitch.js
I did not mock the async calls to neon-js when I originally wrote these tests, which is why I had async issues and needed try/ catch blocks and long setTimeouts. Now the 'neon-js' calls are mocked and it is working correctly.
Testing the neon wallet
By adding in mock functionality for 'neon-js' calls
running 'npm test'
there was one place I left a TODO comment where I put the same code for my axios mock adapter in 2 files. I was unable to make this DRY with my initial attempt and feel that this is an important PR to improve the current …
=> mocking neon-js calls to remove async issues

__mocks__/neon-js.js, __tests__/modules/generateWallet.test.js, app/modules/generateWallet.js
Testing the neon wallet
Testing the generateWallet module
By writing tests for the actions and reducers and mocking the neon-js calls in the reducer
running 'npm test'
=> add test for generateWallet module

__tests__/modules/metadata.test.js, app/modules/metadata.js
Testing neon wallet
Testing the actions and reducers in the metadata module for the neon wallet
by testing the actions and reducers are working correctly
by running 'npm test'
no
=> add tests for metadata module

app/components/Send.js
@shawnmclean I can't comment to your question below because of repository restrictions, so I'm editing this message to answer you.
I might later on, my order of priority would be this: 
- add tests to my own mobile wallet (I'm using neon-wallet as reference for the SDK)
- add tests to neon-js SDK
- add tests here.
=> Add missing return statement to validateForm()

__tests__/modules/transactions.test.js, app/modules/transactions.js
Testing the neon wallet
Testing the transactions module reducers and actions
by writing tests for the actions and reducers functionality
by running 'npm test'
no
=> add tests for transactions module

__tests__/modules/wallet.test.js
Testing Neon Wallet
Testing the wallet module actions and reducers
Testing functionality of wallet module actions and reducers
By running 'npm test'
no
=> add tests for wallet module

__mocks__/neon-js.js, __tests__/modules/generateWallet.test.js, __tests__/store/reducers.test.js
Testing Neon Wallet
Gets tests to pass after changes for rpx ico
fixing tests, running 'npm test'
running 'npm test'
no
=> get tests to pass with rpx changes

__mocks__/neon-js.js, __tests__/components/Send.test.js, __tests__/components/__snapshots__/Send.test.js.snap, app/components/Send.js, app/components/WalletInfo.js
testing the Neon Wallet
testing the Send component
testing the functionality and proper rendering of the component
running npm test
I put a comment in line 225 - there was an issue I was having where 2 actions were getting called after the store.getActions() was being called, but I was unable to find a way to change that. Overall, it seemed a minor enough issue that I submitted the PR and left in the comment. Please let me know if you have any ideas.
no
=> add tests for Send component

app/components/LoginLocalStorage.js, app/components/LoginPrivateKey.js
If one attempts to login with a saved wallet and there is no wallet selected the user receives no feedback of this fact. This update fixes that by adding a notification message to select a wallet.
=> no selected wallet notification

__tests__/components/LoginNep2.test.js, __tests__/components/Send.test.js, __tests__/components/WalletInfo.test.js
Testing Neon Wallet
Second pass through of tests to improve speed and fix some tests so they will now pass with evgeny's changes that include flow. Also, I commented out one test that is currently failing but will pass once evgeny's changes are merged in. I will uncomment that once his changes are in.
changes throughout the test files
yarn test
no
=> fixes and improvements to the test suites

__e2e__/view-balance.e2e.js, package.json, yarn.lock
https://github.com/CityOfZion/neon-wallet/issues/230
* Setup integration test 
* Add first basic test: login, change to testnet, verify balance, verify transaction
* Setup end to end test using Spectron, and test runer AVA
To run test script:
* ``yarn assets``
* ``yarn test:e2e``
No, add __e2e___ test folder only
=> Setup integration test & add first basic test

app/containers/LoginPrivateKey/LoginPrivateKey.jsx, app/modules/account.js
Failed Flow/Lint errors.
Fixed Flow/Lint errors.
yarn flow && yarn lint
No failed errors found!
=> Fix flow and lint errors

.editorconfig
"EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs" (http://editorconfig.org/)
Code style
Added the .editorconfig file in the root directory
Checked the IDE
=> Adds editor config file

.circleci/config.yml, __e2e__/view-balance.e2e.js
#230 
Config to run integration test on CI
=> Run e2e test on CircleCI

__tests__/components/__snapshots__/Login.test.js.snap, app/components/CreateWallet.js, app/components/EncryptKey.js, app/components/LoginLocalStorage.js, app/components/LoginNep2.js, app/components/LoginTokenSale.js, app/containers/LoginPrivateKey/LoginPrivateKey.jsx, app/containers/TokenSale/TokenSale.jsx
None afaik
Just nice to autofocus inputs. Saves a click.
autoFocus attribute.
Click to each component to see.
No
Left out send inputs. Doesn't make as much sense there but will do if you'd like.
Changed a test to keep it working.
=> Add autofocus to inputs

__tests__/ledger/ledgerNanoS.test.js, app/containers/LoginLedgerNanoS/LoginLedgerNanoS.jsx, app/ledger/ledgerNanoS.js, app/modules/account.js, app/modules/claim.js, app/modules/transactions.js, app/styles/main.scss, package.json, yarn.lock
Adding ledger support for Neon Wallet
Updates ledger code to refactor javascript and integrate with neon-js. improved user feedback during ledger usage
added Methods to neon-js and refactored wallet code
Tested with ledger
no. I will add tests for the ledger code soon when we revisit testing for the wallet after the refactor.
no
=> ledger update

app/components/Home/Home.jsx, package.json
=> ledger text fix

app/containers/App/index.js, app/containers/Claim/index.js, app/containers/CreateWallet/index.js, app/containers/Dashboard/index.js, app/containers/EncryptKey/index.js, app/containers/LoginLedgerNanoS/index.js, app/containers/LoginLocalStorage/index.js, app/containers/NetworkSwitch/index.js, app/containers/Send/index.js, app/containers/Settings/index.js, app/containers/TokenSale/index.js, app/containers/TransactionHistory/index.js, app/containers/WalletInfo/index.js, app/modules/account.js, app/modules/claim.js, app/modules/dashboard.js, app/modules/generateWallet.js, app/modules/metadata.js, app/modules/notification.js, app/modules/rpx.js, app/modules/transactions.js, app/modules/wallet.js
tech debt- change the way we grab items from state
by using functions to get items from state -> neo: getNeo(state) vs neo: state.wallet.neo
=> add getters for state

__tests__/components/Send.test.js, __tests__/modules/dashboard.test.js, __tests__/modules/generateWallet.test.js, __tests__/modules/metadata.test.js, __tests__/modules/wallet.test.js, app/modules/account.js, app/modules/claim.js, app/modules/dashboard.js, app/modules/generateWallet.js, app/modules/metadata.js, app/modules/rpx.js, app/modules/wallet.js
refactors all actions to have a payload and fixes the tests to match this pattern as well
=> Payload refactor

app/containers/LoginLocalStorage/LoginLocalStorage.jsx
Just a silly extra character in the UI we don't want to get released
=> Remove exclamation that's not needed in UI

__tests__/components/LoginNep2.test.js, __tests__/components/__snapshots__/Login.test.js.snap, app/containers/CreateWallet/CreateWallet.jsx, app/containers/EncryptKey/EncryptKey.jsx, app/containers/LoginLocalStorage/LoginLocalStorage.jsx, app/containers/LoginNep2/LoginNep2.jsx, app/containers/LoginPrivateKey/LoginPrivateKey.jsx, app/containers/LoginTokenSale/LoginTokenSale.jsx
Simple way to get enter key working in forms
=> Enter in textfields submits alt

__e2e__/view-balance.e2e.js, __mocks__/neon-js.js, __tests__/components/WalletInfo.test.js, app/components/Modals/SendModal/ConfirmDisplay.jsx, app/components/Modals/SendModal/SendModal.jsx, app/components/Modals/SendModal/SendModal.scss, app/containers/Dashboard/Dashboard.jsx, app/containers/Dashboard/index.js, app/containers/WalletInfo/WalletInfo.jsx, app/core/explorer.js, app/modules/notifications.js, app/modules/wallet.js, app/styles/variables.scss
=> Nep5 final changes

app/components/Tooltip/Tooltip.jsx
Bugfixes
Tooltip positioning didn't work properly, it was hard coded for 'bottom'.
Tested
No
=> Pass the prop position to tippy

__tests__/core/explorer.test.js, __tests__/modules/metadata.test.js, app/containers/Settings/Settings.jsx, app/core/constants.js, app/core/explorer.js, app/modules/metadata.js
None
Add NEOVerse explorer (explorer.neoverse.io)
Also, rename EXPLORER to EXPLORERS, and use a loop to iterate the explorer list.
Tested
Yes
=> Add NEOVerse explorer

app/containers/LoginLedgerNanoS/LoginLedgerNanoS.jsx, app/modules/account.js
I added a setInterval and refactored the login process for ledger so it automatically detects if you plug-in or unplug your ledger from the login page
=> Improve Ledger Login Process

__tests__/components/WalletInfo.test.js, app/modules/wallet.js
=> Timing issue

app/containers/LoginLedgerNanoS/LoginLedgerNanoS.jsx, app/core/constants.js, app/modules/account.js
=> improve ledger messages

app/components/Modals/TokenInfoModal/TokenInfoModal.jsx, app/modules/wallet.js, package.json, yarn.lock
Fixes the issue with prices getting rounded to integers:
https://github.com/CityOfZion/neon-js/commit/a8d8bb18f1f6a5fbf395c92ee1a35a690906a0b5
Adjustment made for the following commit which solves the isNaN mystery:
https://github.com/CityOfZion/neon-js/commit/4504367ea9375e9e4bdad81655f42b538f706ffa
=> Upgrade to neon-js 2.2.1

package.json, yarn.lock
Per this issue:
electron-userland/electron-builder#2260
I upgraded electron-builder and now the build works.
This commit originally showed up in the NEP-6 branch but I'm including it here alone to simplify getting it in as it should help everybody.
=> Try upgrading electron-builder to fix build error

app/components/Modals/SendModal/AddRecipientDisplay.jsx, app/components/Modals/SendModal/SendModal.jsx, app/containers/Dashboard/Dashboard.jsx, app/containers/Dashboard/index.js, app/modules/transactions.js
=> Nep5 ledger

app/components/Modals/SendModal/SendModal.jsx, app/containers/Dashboard/Dashboard.jsx
Fix for issue found while QA'ing
net net net net net
=> Fix warning display logic when sending to transaction-less addresses

app/core/math.js
=> Large nep5

__tests__/components/WalletInfo.test.js, __tests__/components/__snapshots__/WalletInfo.test.js.snap, app/containers/WalletInfo/WalletInfo.jsx
Adds NEO formatting to the dashboard
=> Format NEO balance

package.json
=> change version number

app/components/Blockchain/Address/Address.jsx, app/components/Blockchain/Address/index.js, app/components/Blockchain/Transaction/index.js
The explorers were getting the wrong prop, should of been `networkId` instead of `net`
=> Fix explorer bugs

app/core/nep5.js
Adds rounding before converting the value to a number
=> Fix nep5 transfer

__tests__/components/__snapshots__/TransactionHistory.test.js.snap, __tests__/components/__snapshots__/WalletInfo.test.js.snap, app/containers/TransactionHistory/index.js, app/hocs/withNetworkData.js
N/A
It just cleans up a couple `mapProps` calls to use `withProps` instead.
I replaced `mapProps` with `withProps`.
I smoke tested.
N/A
N/A
=> Replaced mapProps with withProps

__tests__/sagas/requestSaga.test.js, __tests__/util/api/createBatchActions.js, __tests__/util/api/createRequestActions.test.js, app/sagas/requestSaga.js
N/A
This fills some holes with regards to the test suite around some of the new redux architecture that was introduced.
I added tests!
`yarn test`
N/A
N/A
=> Backfilled tests for action creators and saga

.circleci/config.yml, __tests__/modules/metadata.test.js, app/components/Modals/TokenSaleModal/TokenSaleModal.jsx, app/core/constants.js
* Added the NRV token sale script hash.
* Enabling mintTokens verification by default.
=> Add NRV and Enable Verification

app/ledger/ledgerNanoS.js, package.json, yarn.lock
- Ledger to properly attach the signature script.
- Ledger to return the Transaction object.
- Update neon-js to v2.3.4
Tested by @brianlenz to ensure verification with ledger works.
=> Fix ledger to attach signature properly and use latest v2 patch

__tests__/actions/blockHeightActions.test.js
N/A
This backfills some tests around block height fetching actions.
I added tests.
I ran the test suite.
N/A
N/A
=> Added tests for block height actions

.circleci/config.yml, package.json
=> upgrade version number

app/core/deprecated.js, app/modules/transactions.js
N/A
When the new actions were introduced, the shape of tokens in the redux store changed.  This was reflected properly when adding/validating individual recipients being added to a transaction in the send modal, but it was not accounted for when confirming/submitting to actually process & send the transaction.
This fixes the balances shape to match the expectations of the validation function.
I smoke tested it and observed the shape in the redux store & breakpoints in the code.
N/A
N/A
=> Fixes validation of tokens when sending a transaction

app/actions/balancesActions.js
N/A
This fixes sending of tokens within the `dev` branch.  The `scriptHash` was not being set as part of the token definition in the redux store.
I added the scriptHash to each token definition in the redux store.
I tried it.
N/A
N/A
=> Fixed scriptHash when building token transaction

__tests__/modules/metadata.test.js, app/core/constants.js, package.json
N/A
Changes defunct NRV token to new, legitimate NRVE token
Updated the code.
Tested it.
No.
No.
No.
=> NRVE token

__mocks__/neon-js.js, __tests__/actions/claimsActions.test.js
N/A
This backfills tests for the claim actions.
I added tests!
I ran the test suite.
N/A
N/A
=> Added tests for claim actions

app/containers/LoginLedgerNanoS/LoginLedgerNanoS.jsx, app/containers/LoginLedgerNanoS/index.js
N/A
The Ledger `publicKey` wasn't being passed to the ledger login action.
I passed the publicKey to the auth action for ledger login.
I asked @snowypowers to try it (since he has a ledger and I don't), and he said it worked. 😄 
N/A
N/A
=> Fixed passing publicKey to ledger login action

__mocks__/neon-js.js, __tests__/actions/claimsActions.test.js, __tests__/components/Claim.test.js, __tests__/components/LoginNep2.test.js, __tests__/components/WalletInfo.test.js, app/actions/balancesActions.js, app/actions/claimsActions.js, app/modules/claim.js, app/modules/transactions.js, package.json, yarn.lock
N/A
This updates the neon-js version within neon-wallet to use v3.3.1.
* Updated neon-js version in `package.json`.
* Various interfaces have been changed to accept/return a `Fixed8` instance instead of a string or number.
* Replaced several `neonDB.doSendAsset` calls with load-balanced `api.sendAsset` calls.
* Replaced `neonDB.doClaimAllGas` with load-balanced `api.claimGas`.
* Replaced `neonDB.getClaims` with `neonDB.getMaxClaimAmount`.
* Removed `asyncWrap` from a couple spots in favor of cleaner try/catch logic.
Smoke tested sending transactions & claiming GAS.  Updated associated tests.
**Are there any …
=> Upgraded neon-js to 3.3.1

app/core/constants.js
Added token contract script hash.
=> Add IAM token script hash

app/ledger/neonLedger.js, config/webpack.config.dev.js, config/webpack.config.prod.js, webpack.config.js, yarn.lock
#798 Issue 2
It also lays in place code for easy adding of new error messages as we come across them.
=> Better error messages for Ledger

__e2e__/view-balance.e2e.js, __mocks__/neon-js.js, app/actions/balancesActions.js, app/actions/blockHeightActions.js, app/actions/claimsActions.js, app/actions/transactionHistoryActions.js, app/components/Modals/SendModal/withAddressCheck.jsx, app/core/formatters.js, app/modules/api/batch.js
Adds Load Balancing to Neon Wallet
Points the methods towards neoscan with neonDB as a fallback
using the api.loadBalance method
QA testing and running the test suites
=> Load balance

package.json
=> update the version

app/modules/claim.js
=> Force neondb for claims

app/containers/WalletInfo/WalletInfo.jsx, app/containers/WalletInfo/index.js
=> fix ico token list

package.json
=> update version to 0.2.1

app/containers/WalletInfo/WalletInfo.jsx, app/containers/WalletInfo/index.js, app/modules/claim.js, package.json
=> Neon Wallet Release 0.2.1

package.json
N/A
Updates neon-wallet version for 0.2.2 release.
N/A
N/A
N/A
N/A
=> Updated version to 0.2.2

README.md
Just to give more insight in newly supported NEP5 tokens at a glance
=> Update README.md with extra NEP5 tokens

release-checklist.md
Updated release checklist as of 0.2.1
Updated functionality including NEP5 tokens, ledger Nano, updated wording including error messages
Updates release checklist to current version of NEON Wallet as at 0.2.1
Tested spec against wallet - Spec noted as being outdated.
Tested & documented
=> neon-wallet/release-checklist.md

app/core/constants.js
N/A
This adds the Switcheo token which has concluded crowdsale on 17 Mar.
I added the scripthash and token symbol for SWH.
I opened the main window and verified that the script hash pulled up the correct token info and amounts.
No
No
=> Add Switcheo token scripthash

app/core/constants.js
Removes NRVE ICO (which has ended).
Added NRVE to `ENDED_ICO_TOKENS`.
=> Remove NRVE ICO

app/containers/LoginLedgerNanoS/LoginLedgerNanoS.jsx, app/containers/LoginLedgerNanoS/index.js, package.json, yarn.lock
N/A
This fixes a call for logging in with ledger.  It also updates to spunky 1.1.2, while accounting for a change in how data & error states are managed in the store.
I made some changes to [spunk](https://github.com/neoverse/spunky) and applied them here.
I smoke tested the ledger login screen.
N/A
N/A
=> Updated to spunky 1.1.2

app/components/Modals/SendModal/SendModal.jsx
Fixed #936.
There was a typo with the phishing address that @drptbl found during QA.
I added a missing word.
N/A
N/A
N/A
=> Fixed wording for phishing message

app/core/constants.js
None
It adds the Effect.AI NEP5 token scripthash to the token list. The contract has been deployed to mainnet
Added the scripthash to the token list
I compiled the code and checked that the token displays correctly
None
No
=> Add Effect.AI token scripthash

ISSUE_TEMPLATE.md
None.
Added template for issues to make them more readable and easier to understand and fix.
Added template to `ISSUE_TEMPLATE.md` file.
Checked it out on my private repository by creating new issue.
Nope.
Nope.
=> Added template for issues

app/modules/claim.js
Fixes #742.
This should hopefully fix many issues related to GAS claim calculations.
Updated to use neoscan instead of neon-wallet-db for calculating claimable GAS.
Ran the app & claimed GAS.
N/A
N/A
=> Updated claims to route through neoscan instead of neon-wallet-db

package.json
N/A
Updates app version to 0.2.4.
Changed version in `package.json`.
N/A
N/A
N/A
=> Updated version to 0.2.4

app/actions/transactionHistoryActions.js, app/modules/claim.js, flow-typed/declarations.js, package.json, yarn.lock
This helps solve the issue of gas claims on ledger that cannot fit onto the ledger. 
Ledger gas claims will be limited to 25 claims per transaction. The theorectical limit is 28 but lets play safe.
Used my ledger and sent myself neo 30 times to generate 30 claims. Checked that my claim fails immediately on 0.2.3. Tried on dev and it worked.
This PR builds on top of the 3.7.0 upgrade.
=> Temp fix for ledger gas claim issue

app/modules/claim.js, app/modules/sale.js, app/modules/transactions.js
N/A
This improves the existing error alerts by providing actual error reasons.  This will better help to track down users when people reach out to support.
I raised appropriate error messages and included the error message in the alert message.
I disabled wifi and tried performing actions such as claiming GAS.
N/A
N/A
=> Updated error alerts to include more detailed messages

app/core/constants.js
None
Lack of MCT token scripthash
Added MCT token scripthash
Tested locally
No
No
=> Add MCT token

yarn.lock
N/A
Broken CircleCI build.
Upgraded upath dependency.
Let CircleCI build & run tests.
N/A
N/A
=> Fixed CircleCI build

app/core/constants.js
N/A
Adds Pikcio Chain scripthash to default list of tokens.
Added PKC symbol & scripthash.
Opened the wallet.
N/A
N/A
=> Added Pikcio Chain (PKC) token

app/components/Modals/SendModal/AddRecipientDisplay.jsx, app/components/Modals/SendModal/AddRecipientDisplay.scss, app/modules/transactions.js
N/A
This backports the removal of 1 drop of GAS requirement from the `design-v2` branch into the `dev` branch.  (See #1062.)
N/A
N/A
N/A
N/A
=> Removed drop of GAS requirement for transfers

app/core/constants.js
N/A
Adds AVA (Travala) token.
Added AVA symbol & scripthash.
Verified it appears in settings.
N/A
N/A
=> Added AVA token

package.json
N/A
Updates version to 0.2.5.
Updated package.json.
N/A
N/A
N/A
=> Updated version to 0.2.5

app/ledger/neonLedger.js
- Message for transaction denied
- Message for parsing error. This is mostly likely due to the NEO app being outdated.
Side effect of getting a ton of lint/prettier changes
=> Add more ledger error msgs

app/components/Contacts/AddContactPanel/AddContactPanel.jsx
Fixes #1144.
The new contact panel header was displaying "Add Contact" instead of "New Contact".
I updated the panel header text.
I ran the app.
N/A
N/A
=> Fixed new contact screen header

app/containers/DisplayWalletAccounts/DisplayWalletAccounts.scss
https://github.com/CityOfZion/neon-wallet/issues/1146
=> vertically center items in DisplayWalletAccounts.jsx

package.json, yarn.lock
N/A
This updates to the latest version of 3.7.3 so that we have all relevant fixes.
Updated `package.json` and `yarn.lock`.
Used the app.
N/A
N/A
=> Updated neon-js to 3.7.3

app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.jsx
https://github.com/CityOfZion/neon-wallet/issues/1021
=> TokenBalancesPanel.jsx is non spammable

app/containers/App/index.js
https://github.com/CityOfZion/neon-wallet/issues/1122
Fixes the problem that was reported by QA (reopened issue)
=> Drop failed progress component for a bad response for prices actions

app/containers/DisplayWalletAccounts/DisplayWalletAccounts.jsx, app/containers/DisplayWalletAccounts/DisplayWalletAccounts.scss
Port the updates from the PR made to dev.
https://github.com/CityOfZion/neon-wallet/pull/1161
*These are random values from a newly created wallet
=> [design-v2] Update new wallet information qrcodes

app/components/Modals/TokenInfoModal/TokenInfoModal.jsx, app/components/Modals/TokenInfoModal/TokenInfoModal.scss, app/containers/WalletInfo/TokenBalances.jsx, app/containers/WalletInfo/TokenBalances.scss, app/core/constants.js, flow-typed/declarations.js
=> Add some warnings for deprecated tokens

__tests__/components/Blockchain/Address/Address.test.js, app/components/Blockchain/Address/Address.jsx
https://github.com/CityOfZion/neon-wallet/issues/1195
Improves functional testing of Address component
- Re-worked component code to properly export functions for mocking
- Built wallet, confirmed that the address button is still clickable
N/A
=> Add address tests

app/actions/appActions.js, app/actions/assetBalancesPanelActions.js, app/actions/dashboardActions.js, app/actions/portfolioPanelActions.js, app/components/Dashboard/AssetBalancesPanel/index.js, app/components/Dashboard/PortfolioPanel/index.js, app/containers/App/index.js, app/containers/Dashboard/index.js
None. It fixes a lot of ```//TODO```s though
Batch actions were being created within index.js files
As instructed by the ```//TODO``` comments, I moved everything into its own file under app/actions.
I tried running the wallet. All the modified components still load correctly
=> Moved batch actions separate files

.circleci/config.yml, __e2e__/view-balance.e2e.js
#1216 
e2e tests don't build correctly
First, I tried to fix the issue by correcting various typos in the e2e test files. I managed to get everything working on my laptop, but CircleCI still had errors. At the recommendation of others working on the project, I removed CircleCI e2e support on the design-v2 branch altogether
I ran ```yarn test:e2e```. That worked on my local machine. Since e2e tests aren't being run on CircleCI, the whole build cycle succeeds now.
=> Fixed e2e tests (fixes #1216)

app/components/Inputs/AddressInput/AddressInput.jsx
#1221
There was an issue with how properties were being bubbled down to text input fields. Errors were being thrown in the console.
I prevented the "dispatch" props attribute from being carried over to text inputs
I made sure inputs were still correctly passing data
=> Fixed invalid dispatch error

.storybook/addons.js, .storybook/config.js, .storybook/webpack.config.js, config/paths.js, config/webpack.config.dev.js, config/webpack.config.prod.js, package.json, stories/components/Button.stories.jsx, stories/components/Loader.stories.jsx, stories/components/index.js, stories/index.js, yarn.lock
N/A
Adds storybook (https://storybook.js.org/) for faster development and component library.
Followed the guide on https://storybook.js.org/
`yarn storybook`
-
-
=> feat(app): Adds storybook and pretty paths

app/core/constants.js
None. Adding in the FiatPEG USD token support.
PEGUSD balances not automatically shown in the wallet
Added the PEGUSD to the constants.js file. Added to the ENDED_ICO_TOKEN (we have no ICO)
Copied what other commits had done
None.
No.
=> Added FiatPEG USD token

app/core/constants.js
None, just adding a nep5 token for spotcoin.com.  We are on the mainnet and we have started our pre-ico already.
SPOT not listed in the NEP5 token list.
Added the SPOT into the constants.js and as a comment in the ENDED_ICO_TOKEN.
I checked against previous NEP5 adds and did exactly the same thing. :) 
no, just did what everyone else did. 
no.
=> added SPOT to list of NEP5 Tokens'

app/modules/vote.js, flow-typed/declarations.js
#1291 
Adds a simple redux action wrapper for neon-js `setupVote`. It displays notification messages for success/failure.
=> Adds setupVote

app/components/Dashboard/PortfolioPanel/PortfolioPanel.scss, app/components/Dashboard/PriceHistoryPanel/PriceHistoryChart.jsx, app/components/Dashboard/PriceHistoryPanel/PriceHistoryChart.scss, app/components/Dashboard/PriceHistoryPanel/PriceHistoryPanel.scss, app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.jsx, app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.scss, app/containers/Dashboard/Dashboard.scss, package.json, yarn.lock
https://github.com/CityOfZion/neon-wallet/issues/1343
This PR also fixes some other bugs in design at large screen resolutions
=> polishes responsive design in dashboard

app/index.js, app/index.tpl.html, config/paths.js, main.js
https://github.com/CityOfZion/neon-wallet/issues/1432
Addresses warnings displayed in development mode https://electronjs.org/docs/tutorial/security
=> addresses numerous electron security vulnerabilities

app/containers/Settings/Settings.jsx
https://github.com/CityOfZion/neon-wallet/issues/1436
=> fixes default explorer bug

app/components/NodeSelectPanel/NodeSelectPanel.jsx, app/components/NodeSelectPanel/NodeSelectPanel.scss
https://github.com/CityOfZion/neon-wallet/issues/1435
=> fixes potential spam vulnerability

app/actions/balancesActions.js, app/components/Contacts/EditContactPanel/EditContactPanel.jsx, app/containers/LoginLocalStorage/LoginLocalStorage.jsx, app/containers/Notifications/Notifications.jsx, app/containers/Notifications/overrideStyles.js, app/index.js, app/index.tpl.html
It was discovered that when clearing all data from Neon wallet via deleting Neon in /Application Support that the application would crash on start. This PR addresses that bug and also the following:
- Styles the info notification
- Removes the Content-Security-Policy which was breaking code being executed from neon-js
- removes the override of window.eval (neon-js requires this) 👆 
FIXES https://github.com/CityOfZion/neon-wallet/issues/1434
=> [WIP] Feature/fixes bug in login

app/components/Contacts/ContactsPanel/ContactsPanel.jsx
N/A
The edit contact button was broken
I removed the extra function which swallowed the action
Tested it manually
N/A
N/A
=> Fixes contacts edit button

app/components/Contacts/ContactsPanel/ContactsPanel.jsx, app/components/Contacts/ContactsPanel/ContactsPanel.scss, app/components/Contacts/EditContactPanel/EditContactPanel.jsx
N/A
Adds sorting, grouping and UI fixes to the contacts page. Additionally I have removed the unused function `handleDelete` from `ContactsPanel` and some used variable in the `EditContactPanel`
Converted the contacts object an an array collection, used lodash `groupBy` to group them by their first letter, then used `orderBy` to sort the groups and the contacts in the groups.
Tested it and verified UI/UX matched the required design.
Nope.
Nope.
=> Adds grouping, sorting and ui fixes to contacts

app/components/Panel/FullHeightPanel/FullHeightPanel.jsx, app/components/Panel/FullHeightPanel/FullHeightPanel.scss, app/containers/CreateWallet/CreateWallet.jsx
https://github.com/CityOfZion/neon-wallet/issues/1461
https://github.com/CityOfZion/neon-wallet/issues/1470
=> [design-review] Implements design change to FullHeightPanel.jsx

__tests__/modules/notifications.test.js, app/containers/Notifications/Notification.scss, app/containers/Notifications/overrideStyles.js, app/modules/notifications.js
https://github.com/CityOfZion/neon-wallet/issues/1465
=> [design-review] notification style updates

__tests__/components/TransactionHistoryPanel.test.js, app/actions/transactionHistoryActions.js, app/components/Blockchain/Transaction/Transaction.jsx, app/components/Blockchain/Transaction/Transaction.scss, app/components/Blockchain/Transaction/index.js, app/components/Button/Button.scss, app/components/Contacts/ContactForm/ContactForm.jsx, app/components/Contacts/ContactForm/ContactForm.scss, app/components/Modals/AddContactModal/AddContactModal.jsx, app/components/Send/SendPanel/SendSuccess/SendSuccessTransaction/SendSuccessTransaction.jsx, app/components/TransactionHistory/TransactionHistoryPanel/TransactionHistoryPanel.scss, app/containers/TransactionHistory/TransactionHistory.jsx
https://github.com/CityOfZion/neon-wallet/issues/1466
- Updates tx history UI per design review
- fixes broken layout of add contact modal
- Parses transactions to see if they come from an address in contacts and adds label with tooltip if found
=> [design-review] transaction history updates

__tests__/components/Send.test.js, app/components/Send/SendPanel/SendPanel.scss, app/components/Send/SendPanel/SendPanelHeader/index.jsx, app/components/Send/SendPanel/SendRecipientList/SendRecipientListItem/index.jsx, app/components/Send/SendPanel/index.jsx, app/containers/Send/Send.jsx
https://github.com/CityOfZion/neon-wallet/issues/1467
- Updates layout and sizing of send panel
- Repositions coming soon tooltip
- Updates icon colors in panel header
- Disables "Add recipient" until details are filled in per row
-  Bumps arbitrary recipient cap up to 10 from 5
=> [design-review] send

app/components/Inputs/SelectInput/SelectInput.scss, app/components/Inputs/StyledReactSelect/StyledReactSelect.jsx, app/styles/main.global.scss
- Updates styling of (both) select components according to design review
NOTE: A future PR will deprecate the "old" select component in favor of our new implementation however that is not within the scope of the design-review task
=> [design-review] select

app/components/NodeSelectPanel/NodeSelectPanel.scss, app/components/Panel/FullHeightPanel/FullHeightPanel.scss
- Increases margin between icon and header text in FullHeighPanel.jsx
- Changes icon colors in node selection to be consistent with the rest of the app
=> [design-review] node selection

__tests__/components/__snapshots__/Logout.test.js.snap
=> fixes tests

app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.jsx, app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.scss, app/components/ZeroAssets/ZeroAssets.jsx
fixes https://github.com/CityOfZion/neon-wallet/issues/1499
=> adds styled receive link to dashboard

app/containers/DisplayWalletAccounts/DisplayWalletAccounts.jsx, app/containers/DisplayWalletAccounts/DisplayWalletAccounts.scss
Fixes https://github.com/CityOfZion/neon-wallet/issues/1453
and gives some polish to the design of the DisplayWalletAccounts component.
=> hides password and fixes layout

app/components/Dashboard/AssetBalancesPanel/AssetBalancesPanel.scss, app/containers/Dashboard/Dashboard.jsx, app/containers/Dashboard/Dashboard.scss
As per review with design this PR adds the label "My Public Address:" to the address link in dashboard and updates a font size in the asset balances panel
=> minor dashboard tweaks

app/actions/pricesActions.js
Because coinmarketcap is deprecating their public facing API this PR switches the pricing data to be pulled from cryptocompare instead.
=> leverages crypto compare for pricing data

app/components/Modals/TokenModal/TokenModal.scss, app/containers/Send/Send.jsx
fixes https://github.com/CityOfZion/neon-wallet/issues/1520
=> fixes padding issue in token modal

app/components/Send/SendPanel/SendRecipientList/SendRecipientListItem/index.jsx
- Reverts the most recent feature that adds nns name lookups - leaves the util file there for future implementation
=> updates SendRecipientListItem/index.jsx

app/components/Send/SendPanel/SendRecipientList/SendRecipientListItem/index.jsx
- fixes https://github.com/CityOfZion/neon-wallet/issues/1522
- depends on https://github.com/CityOfZion/neon-wallet/pull/1529
=> fixes exception crashing the app

app/components/Dashboard/AssetBalancesPanel/AssetBalancesPanel.scss, app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.jsx, app/containers/Dashboard/Dashboard.scss, main.js
- Fixes https://github.com/CityOfZion/neon-wallet/issues/1517
=> reduces minimum browser window size

app/components/Contacts/ContactForm/ContactForm.scss
fixes https://github.com/CityOfZion/neon-wallet/issues/1537
=> fixes padding defect in ContactForm.scss

app/components/Dashboard/AssetBalancesPanel/AssetBalancesPanel.jsx, app/components/Dashboard/AssetBalancesPanel/index.js, app/components/Dashboard/PortfolioPanel/PortfolioPanel.jsx, app/components/Dashboard/PortfolioPanel/index.js
fixes https://github.com/CityOfZion/neon-wallet/issues/1545
=> updates panel headers in dashboard

app/actions/nodeStorageActions.js, app/components/Modals/BaseModal/BaseModal.scss, app/components/PanelHeaderButton/PanelHeaderButton.scss, app/components/Send/SendPanel/SendPanel.scss
- Fixes bug causing app to crash with new node selection implementation
- Fixes color of icon in full height modal
=> fixes bug in node selection work

app/core/tokenList.json
=> updates tokenList.json

app/components/Blockchain/Transaction/Transaction.jsx, app/components/Blockchain/Transaction/Transaction.scss, app/components/Blockchain/Transaction/index.js, app/core/tokenList.json
fixes https://github.com/CityOfZion/neon-wallet/issues/1591
=> aligns contacts to left and removes ability to add self on claim

ICOTokens.json, app/actions/priceHistoryActions.js, app/actions/pricesActions.js, app/components/Dashboard/PriceHistoryPanel/PriceHistoryChart.jsx, app/components/Dashboard/PriceHistoryPanel/index.js, app/components/FailedPanel/FailedPanel.jsx, app/components/Send/SendPanel/SendRecipientList/SendRecipientListItem/index.jsx, app/containers/Send/Send.jsx, app/core/formatters.js
- fixes https://github.com/CityOfZion/neon-wallet/issues/1620
- once and for all fixes https://github.com/CityOfZion/neon-wallet/issues/1573
- Adds link to node select on dashboard when request to RPC node fails offering a work around for https://github.com/CityOfZion/neon-wallet/issues/1627
- Sets default to 1d on price chart
- Updates price chart Y axis to include cent values https://github.com/CityOfZion/neon-wallet/issues/1629
- Puts back nOS script hash in ico list
=> fixes various release defects

app/actions/balancesActions.js, app/components/Modals/TokenModal/TokenModal.jsx, app/hocs/withTokensData.js
- Fixes https://github.com/CityOfZion/neon-wallet/issues/1632
=> adding a token updates balances

app/components/Blockchain/Transaction/Transaction.jsx, app/components/Blockchain/Transaction/Transaction.scss, app/components/Contacts/ContactsPanel/ContactsPanel.jsx, app/components/Contacts/ContactsPanel/ContactsPanel.scss, app/components/Dashboard/TokenBalancesPanel/TokenBalancesPanel.jsx, app/components/Receive/QRCodeForm/QrCodeForm.jsx, app/components/Receive/QRCodeForm/styles.scss, app/components/Receive/ReceivePanel/styles.scss, app/components/Send/SendPanel/SendRecipientList/SendRecipientListItem/index.jsx, app/containers/Send/Send.jsx
- Fixes potential text overflow bugs discovered by @fabwa in Contacts and Activity
- Adds additional validation to Receive QR generation fixing bugs discovered by @fabwa 
- Fixes issue preventing users from typing in Address in Send manually
- Adds additional validation to Send to prevent users from being able to attempt to send more assets than they currently have (cumulatively) in addition to validating each send row
- fixes https://github.com/CityOfZion/neon-wallet/issues/1636
=> various defect fixes

app/actions/balancesActions.js, app/components/Button/Button.scss, app/components/Send/PriorityFee/PriorityFee.jsx, app/components/Send/PriorityFee/PriorityFee.scss, app/components/Send/SendPanel/SendSuccess/SendSuccessTransaction/SendSuccessTransaction.jsx, app/components/Send/SendPanel/SendSuccess/SendSuccessTransaction/index.js, app/components/Send/SendPanel/SendSuccess/index.jsx, app/containers/DisplayWalletAccounts/DisplayWalletAccounts.jsx, app/core/networks.js, app/modules/sale.js, app/modules/transactions.js, app/themes/Dark.js
- selected node now applies to token sale and send tx
- gas fee applied in token sale
- Fixes styling in dark theme of priority fee button
- adds the ability to toggle priority fee button
- Corrects verbiage in send confirmation updating TRANSACTIONS => TRANSFERS
- Fixes link in confirmation success to use selected explorer
- Filters custom added hashes by network in balancesActions.js (reducing unnecessary requests and eliminating error being thrown in console)
- Fixes navigation in authenticated version of confirmation qr codes close button
=> feature: various defect fixes

app/containers/DisplayWalletAccounts/DisplayWalletAccounts.scss, app/containers/DisplayWalletAccounts/PrintPage.jsx
- Increases widths of inputs
- Fixes margin of button row
=> feature: fixes style bugs in DisplayWalletAccounts.jsx

ICOTokens.json, app/components/Send/SendPanel/ConfirmSend/index.jsx, app/components/Send/SendPanel/SendRecipientList/SendRecipientListItem/index.jsx, app/components/Send/SendPanel/SendRecipientList/index.jsx, app/components/Send/SendPanel/index.jsx, app/containers/Send/Send.jsx
- fixes https://github.com/CityOfZion/neon-wallet/issues/1577
=> feature: fix max amount calc in Send

app/components/NodeSelectPanel/index.js
- Fixes a defect requiring a user to return to dashboard in order for balance data to load after choosing a new node
=> feature: fixes node select balance load defect

app/containers/CreateWallet/CreateWallet.jsx
Fixes #1619 
Utilized the input error message mechanism. Nothing fancy. Pretty straight forward.
No new tests added.
Password validator - at least 4 chars
Confirm validator - matches password
(Empty fields show no error message since it's redundant and bad for UX)
Feel free to suggest alternative error message texts.
=> [#1619] New wallet form validation

app/actions/balancesActions.js, app/actions/icoTokensActions.js, app/actions/nodeNetworkActions.js, app/actions/nodeStorageActions.js, app/core/constants.js, app/core/networks.js, app/modules/sale.js, app/modules/transactions.js
- This PR makes it so that by default during automatic node select we exclude ngd and neo.org RPC nodes. This also makes it so that we are not dependent on neoscan for automatic node selection
- This PR also removes depending on neoscan for automatic node selection
=> featue: updates node auto select logic

app/components/Send/SendPanel/SendSuccess/index.jsx
- fixes https://github.com/CityOfZion/neon-wallet/issues/1669
=> feature: fixes send success tx timestamp

app/components/Receive/QRCodeForm/QrCodeForm.jsx, app/components/Receive/ReceivePanel/styles.scss
- during regression testing I realized that there was a small defect in the validation func for nep9 QR generation. This PR fixes that issue.
- This PR also sets the receive panel to 100% height (just like the others)
=> fixes defect in receive validation

app/actions/pricesActions.js
https://github.com/CityOfZion/neon-wallet/issues/1747
by comparing the newly returned results to pricing data on coinmarketcap
=> feature: fixes Phantasma pricing data

app/components/Modals/SendModal/ReadCode/ReadCode.jsx, app/components/Modals/SendModal/ReadCode/ReadCode.scss, app/components/QrCodeScanner/QrCodeScanner.jsx, app/components/QrCodeScanner/QrCodeScanner.scss, app/containers/App/Loading.js, app/containers/Home/Home.scss, app/containers/LoginPrivateKey/LoginPrivateKey.jsx, flow-typed/declarations.js, package.json, yarn.lock
This is one of a bunch of commits changing the QR Scan code to be more performant, better and simpler code, with full control of all feature aspects and more visually appealing (in later commits).
We use [Instascan](https://www.npmjs.com/package/instascan) for our qr scan feature but it's 1) bloated 2) abandoned 3) doesn't allow full control.
Implemented our own video preview, image capture and scan logic. The QR code analysis itself is done with [jsqr](https://www.npmjs.com/package/jsqr).
There is no change in functionality in this commit.
Had a hard time making tests for this feature as it requires mocking …
=> Perf optimization for QR Scanner (Instascan->jsqr)

app/components/Blockchain/Transaction/PendingAbstract.jsx, app/components/Blockchain/Transaction/SendAbstract.jsx
None - verbally spoken to Max
Removes unnecessary brackets to obtain cleaner code
by removing them
testing it
/
/
=> chore(Blockchain): removed unnecessary brackets

app/actions/nodeStorageActions.js, app/components/Dashboard/AssetBalancesPanel/AssetBalancesPanel.jsx, app/components/Dashboard/AssetBalancesPanel/index.js, app/components/Dashboard/PriceHistoryPanel/PriceHistoryChart.jsx, app/components/Dashboard/PriceHistoryPanel/PriceHistoryPanel.jsx, app/components/Dashboard/PriceHistoryPanel/index.js
https://github.com/CityOfZion/neon-wallet/pull/1780
=> hotfix: fixes bug causing app to crash due to missing historical price info

app/components/Contacts/ContactsPanel/ContactsPanel.jsx, app/components/Contacts/ContactsPanel/ContactsPanel.scss
No issue currently open
It looks like the PR to add "delete" functionality to the contacts page broke the layout... This PR adjusts the spacing to fix the issue
By removing unnecessary text from the "actions" as well as reducing padding
Running on a windows VM manually and manually checking the macOS build
=> chore: fixes contacts layout

app/components/Contacts/ContactForm/ContactForm.jsx
https://github.com/CityOfZion/neon-wallet/issues/1662
Presently with the way the form is written there is no feedback in the UI when a user has added invalid details this small change provides that feedback via the error prop on the <TextInput/> component
By validating the user input as its added to the form rather than when it is submitted.
Manual testing
=> feature: refactors validation in ContactForm.jsx

__tests__/components/__snapshots__/News.test.js.snap, app/containers/News/News.jsx, package-lock.json
https://github.com/CityOfZion/neon-wallet/issues/1842
https://github.com/CityOfZion/neon-wallet/issues/1842
Added event listener to news feed panel to see if you have reached the bottom of the page. Then paginates and sets the state when you reach the bottom. 
Manual testing through Electron
=> Adds infinite scroll via pagination to newsfeed

__e2e__/verifySideNav.e2e.js
1st PR - Adds automated testing for the side nav routes and UI
(builds off of the work started in the `feature/end-to-end-tests` branch)
=> added verifySideNav

app/containers/LoginWatchOnly/LoginWatchOnly.jsx
https://github.com/CityOfZion/neon-wallet/pull/1847
=> feature: watch address II

app/containers/LoginWatchOnly/LoginWatchOnly.jsx
This PR simply removes the styling making the watch only input have smaller than default text...
=> chore: update input text size

package.json, yarn.lock
https://yarnpkg.com/en/docs/selective-version-resolutions
=> chore: fixes github fstream vulnerability

.circleci/config.yml, package.json, yarn.lock
=> chore: Fixes github security alerts regarding npm deps

app/core/tokenList.json
Updated hash of NNN token and added link to logo.
Depends on [neo-tokens pr](https://github.com/CityOfZion/neo-tokens/pull/56) for the logo.
=> Updated NNN token hash and name and added link to logo

app/components/CreateImportWalletForm/CreateImportWalletForm.jsx, app/components/CreateImportWalletForm/CreateImportWalletForm.scss, app/containers/CreateImportWallet/ImportWallet/ImportWallet.jsx, app/containers/CreateImportWallet/ImportWallet/ImportWallet.scss
Fixes some minor style bugs discovered while regression testing the release candidate:
BEFORE:
- Some inconsistent and weird spacing
- Undesirable effects when increasing window size from default
AFTER:
=> feature: minor style updates to release

app/containers/Dashboard/Dashboard.jsx, app/containers/Dashboard/Dashboard.scss
=> feature: Fixes alignment and layout of public key / address on dashboard

app/actions/nodeNetworkActions.js, app/actions/nodeStorageActions.js, app/core/nodes-main-net.json
No issue currently open
This PR updates the hard coded list in `nodes-main-net.json` to the current results returned from https://api.neoscan.io/api/main_net/v1/get_all_nodes
Manual testing locally
=> feature: updates node list

__tests__/actions/authActions.test.js, __tests__/actions/claimsActions.test.js, __tests__/modules/generateWallet.test.js, __tests__/setupTests.js, app/actions/accountsActions.js, app/actions/authActions.js, app/components/CreateImportSplitWalletForm/CreateImportSplitWalletForm.jsx, app/core/constants.js, app/modules/generateWallet.js
=> feature: neon 5 auth (neo3)

app/components/Receive/ReceiveExplanation/styles.scss, app/components/Root/IntlWrapper.jsx, app/core/constants.js, app/translations/index.js, app/translations/vietnamese.js
=> feature: Vietnamese implementation

app/components/Root/IntlWrapper.jsx, app/core/constants.js, app/translations/chinese.js, app/translations/german.js, app/translations/index.js
=> feature: Chinese implementation

__tests__/components/Dashboard/PortfolioPanel.test.js, __tests__/components/__snapshots__/Sidebar.test.js.snap, app/components/LogoWithTooltipAndBlockHeight/LogoWithTooltipAndBlockHeight.jsx, app/styles/main.global.scss, app/themes/Dark.js, app/themes/Light.js, yarn.lock
=> feature: Fixes buggy CSS for network config tooltip

__tests__/components/Modals/__snapshots__/ConfirmModal.test.js.snap, __tests__/components/__snapshots__/NetworkConfigurationTooltip.test.js.snap, app/components/Button/Button.jsx, app/components/Button/Button.scss, app/themes/Dark.js, app/themes/Light.js
=> feature: implement button reskin

app/components/Panel/FullHeightPanel/FullHeightPanel.jsx, app/components/Panel/FullHeightPanel/FullHeightPanel.scss
=> feature: fixes issues with FullHeightPanel.jsx

app/actions/balancesActions.js, package.json
=> hotfix: Fix balance bug ang dmg background image

app/actions/balancesActions.js, package.json
=> hotfix: Fix balance bug and dmg background image

.circleci/config.yml, __tests__/components/__snapshots__/Settings.test.js.snap, app/containers/Home/Home.jsx, package.json
TODO:
~- `publish` should only be run on tag builds~
=> feature: skip testing on tags [WIP]

app/core/constants.js, app/core/nodes-main-net.json
- Removes dead CoZ nodes
- Adds back NGD nodes which appear healthy
=> featute: Updates mainnet node list

app/components/Modals/ReleaseNotesModal/ReleaseNotesModal.jsx
=> feature: Updates release notes for patch 2.6.1

__tests__/core/explorer.test.js, app/components/Modals/ReleaseNotesModal/ReleaseNotesModal.jsx, app/components/Modals/ReleaseNotesModal/ReleaseNotesModal.scss, app/core/constants.js, app/core/explorer.js
Adds new explorers to the explorer settings dropdown:
https://dora.coz.io/
https://neotube.io/
=> feature: adds dora and neotube to explorers

app/actions/balancesActions.js, app/core/nodes-main-net.json
=> feature: Updates app/core/nodes-main-net.json with new coz nodes

app/assets/images/release-assets/patch-dark.svg, app/assets/images/release-assets/patch-light.svg, app/assets/images/release-assets/patch.svg, app/components/Modals/ReleaseNotesModal/ReleaseNotesModal.jsx, app/components/Modals/ReleaseNotesModal/ReleaseNotesModal.scss
=> feature: update release notes [WIP]

package.json, yarn.lock
=> feature: Removes react-syntax-highlighter

app/containers/Home/Home.jsx
=> hotfix: Add patch to whitelist

app/core/nodes-test-net.json
This PR updates the testnet Neo node list to reenable testnet support for the wallet.
=> update testnet node list

app/containers/Mobile/Mobile.jsx
=> feature: replace lorem ipsum copy in Mobile.jsx

app/components/Modals/ShowQrForExportModal/ShowQrForExportModal.jsx
=> feature: Updates the export codes to conform to new schema

app/actions/balancesActions.js, app/actions/pendingTransactionActions.js, app/actions/transactionHistoryActions.js, app/components/Blockchain/Transaction/Transaction.jsx, app/components/Blockchain/Transaction/index.js, app/components/Modals/ShowQrForExportModal/ShowQrForExportModal.scss, app/containers/Receive/Receive.jsx, app/core/explorer.js, app/modules/transactions.js, app/util/findAndReturnTokenInfo.js
TODO:
- Fix dora/neotube linking
- Fix hardcoded GAS image
=> feature: support for activity screen

app/hocs/helpers/didLogout.js
Previously logging out was not clearing the redux state tree where needed... This PR fixes that!
=> feature: fixes reset check

app/actions/contactsActions.js, app/components/Blockchain/Address/Address.jsx, app/components/Contacts/ContactsPanel/ContactsPanel.jsx, app/core/explorer.js
=> feature: fix broken build

app/actions/n3AccountsActions.js
https://github.com/CityOfZion/neon-wallet/issues/2151
=> feature: Fixes bug with stored wallet retrieval

app/components/Dashboard/AssetBalancesPanel/AssetBalancesPanel.jsx, app/components/Dashboard/AssetBalancesPanel/index.js, app/components/Send/N3Fees/N3Fees.jsx, app/components/Send/N3Fees/N3Fees.scss, app/components/Send/N3Fees/index.js, app/components/Send/SendPanel/index.jsx, app/containers/Send/Send.jsx, app/containers/Send/index.js, app/modules/transactions.js
=> feature: add n3 fee data to UI

app/actions/claimsActions.js, app/components/Dashboard/AssetBalancesPanel/AssetBalancesPanel.jsx, app/containers/Claim/Claim.jsx, app/containers/Claim/index.js, app/modules/claim.js
=> feature: adds n3 GAS claim flow

__tests__/components/__snapshots__/NetworkConfigurationTooltip.test.js.snap, __tests__/components/__snapshots__/Settings.test.js.snap, __tests__/components/__snapshots__/Sidebar.test.js.snap, app/actions/balancesActions.js, app/actions/blockHeightActions.js, app/actions/claimsActions.js, app/actions/dashboardActions.js, app/actions/nodeNetworkActions.js, app/actions/nodeStorageActions.js, app/components/NetworkConfigurationTooltip/NetworkConfigurationTooltip.jsx, app/components/NetworkConfigurationTooltip/index.js, app/containers/App/Sidebar/NetworkSwitch/NetworkSwitch.jsx, app/containers/App/Sidebar/NetworkSwitch/index.js, app/containers/App/Sidebar/index.js, app/containers/Settings/Settings.jsx, app/containers/Settings/index.js, app/core/constants.js, app/core/n3-nodes-main-net.json, app/core/n3-nodes-test-net.json, app/core/networks.js, app/modules/claim.js, app/modules/transactions.js, app/util/findAndReturnTokenInfo.js
(currently wired to RC3 for testing purposes)
=> feature: network configuration / node select
